### ISSUE TITLE
请将欧冶云商添加到钻石赞助商

### ISSUE THREAD

**Issue by newmike** [PyConChina/PyConCN#100]
LOGO请见文件

![ouyeel](https://cloud.githubusercontent.com/assets/6406988/9703030/63af266a-54a8-11e5-8f14-cae15f242ecc.png)

**Comment by ZoomQuiet** [comment]
官网链接
中E文简述请提供

2015-09-06 14:25 GMT+08:00 Mike Zhang notifications@github.com:

> LOGO请见文件
> http://yunpan.cn/cmvu9U2jMv8XS 访问密码 abd6
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/100.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by newmike** [comment]
上海钢铁交易中心（http://www.shgt.com/）是隶属于欧冶云商旗下的钢铁B2B电商平台。作为“互联网+钢铁”的先驱者，致力于为上下游企业提供交易、物流、加工、金融、技术、信息等全流程一站式服务，创造超越期望的价值体验。
经过两年多的发展，客户数已经超过8.５万家 ，交易量超过1，060万吨 ，结算金额超过3００亿元 ，以其高度智能化的系统、专业可靠的服务走在了同行前列，目标在3年内成为全球第一的钢铁电商网站。
智慧平台，让钢铁交易更简单。
