### ISSUE TITLE
请将中国科技网LOGO替换成浦东软件园

### ISSUE THREAD

**Issue by newmike** [PyConChina/PyConCN#101]
![default](https://cloud.githubusercontent.com/assets/6406988/9702962/26afd2a2-54a6-11e5-810a-22fcb035ded6.png)

**Comment by ZoomQuiet** [comment]
其它信息呢?!

**Comment by newmike** [comment]
就是合作方啊，提供的上海场地支持，还需要什么信息？

**Comment by ZoomQuiet** [comment]
和其它任何赞助/合作 方一样的哪
- 中E文简介
- 官方网站地址

不能白板一个logo 哪

On Sun, Sep 6, 2015 at 3:13 PM, Mike Zhang notifications@github.com wrote:

> 就是合作方啊，提供的上海场地支持，还需要什么信息？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/101#issuecomment-138049099.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by newmike** [comment]
上海浦东软件园是上海乃至全国的软件产品、技术和人才的集散地,拥有健全的基础设施配套、共性的技术支撑平台、良好的企业服务体系、必要的生产力要素市场、完善的企业创新与孵化机制、强大的产业集群力量，从而成为可供居住、学习、工作及休闲娱乐为一体的全方位生态社区。
上海浦东软件园致力于打造世界级软件产业创新社区。

**Comment by newmike** [comment]
http://www.spsp.com.cn/
