### ISSUE TITLE
[speech]Gz:郑和柳 Robert Zheng 机智云

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#102]
# 郑和柳 Robert Zheng

目前在机智云担任 Python 程序员，09 年开始接触 Python，用 Python 写过嵌入式程序、手机程序（Symbian，Android）、桌面程序（PyQT）、Web 程序（主要是 Django）等等。一个爱运动的技术宅，微博 @ax003d
## 用 Python 实现 DDNS 以及在 Docker 中的应用

讲述 DDNS （动态域名解析）原理，如何将自己注册的域名指向自己的 DNS 服务器，以及通过 Python 搭建自己的二级域名 DDNS 服务。另外，还结合 Docker 技术，讲述 DDNS 在 Docker 实践中的应用。
![gizwits_avatar](https://cloud.githubusercontent.com/assets/22494/9705182/9768e144-54ee-11e5-8868-c86a2fddd342.jpg)

**Comment by ax003d** [comment]
Hi, Zoom.Quiet,

纠正下，卢奕卿 Yuki Lu 是我们公司市场部的同事的名字，我的名字叫做：郑和柳 Robert Zheng。
谢谢！

在 2015年9月6日 下午11:25，Zoom.Quiet notifications@github.com写道：

**Comment by ZoomQuiet** [comment]
got it ;-)

2015-09-06 23:29 GMT+08:00 ax003d notifications@github.com:

> Hi, Zoom.Quiet,
> 
> 纠正下，卢奕卿 Yuki Lu 是我们公司市场部的同事的名字，我的名字叫做：郑和柳 Robert Zheng。
> 谢谢！
> 
> 在 2015年9月6日 下午11:25，Zoom.Quiet notifications@github.com写道：
> 
> > 卢奕卿 Yuki Lu
> > 
> > 目前在机智云担任 Python 程序员，09 年开始接触 Python，用 Python
> > 写过嵌入式程序、手机程序（Symbian，Android）、桌面程序（PyQT）、Web 程序（主要是
> > Django）等等。一个爱运动的技术宅，微博
> > @ax003d https://github.com/ax003d
> > 用 Python 实现 DDNS 以及在 Docker 中的应用
> > 
> > 讲述 DDNS （动态域名解析）原理，如何将自己注册的域名指向自己的 DNS 服务器，以及通过 Python 搭建自己的二级域名 DDNS
> > 服务。另外，还结合 Docker 技术，讲述 DDNS 在 Docker 实践中的应用。
> > [image: gizwits_avatar]
> > <
> > https://cloud.githubusercontent.com/assets/22494/9705182/9768e144-54ee-11e5-8868-c86a2fddd342.jpg>
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/PyConChina/PyConCN/issues/102.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/102#issuecomment-138093271.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
