### ISSUE TITLE
[speech]Sh+GZ: 孔令开 (欧冶云商 )

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#103]
# 孔令开
## 简单实用的自制Rest API工具

一个简单的小工具，一秒五行写出pythonic的api接口，自动生成接口文档，js调用代码，ios客户端调用代码，ng调用代码...

**Comment by newmike** [comment]
演讲主题：
简单实用的自制Rest API工具
简介：
一个简单的小工具，一秒五行写出pythonic的api接口，自动生成接口文档，js调用代码，ios客户端调用代码，ng调用代码...

演讲人姓名：
孔令开
简介：
孔令开，曾在微软服务器与工具部门任高级工程师，负责开发家庭服务器与中小企业服务器。微软毕业后投身钢铁电商，负责上海钢铁交易中心技术架构，热爱python以及开源项目，对搜索引擎以及各种创业项目十分关注。

公司简介：
上海钢铁交易中心（SHGT.com）是隶属于欧冶云商旗下的钢铁B2B电商平台。作为“互联网+钢铁”的先驱者，致力于为上下游企业提供交易、物流、加工、金融、技术、信息等全流程一站式服务，创造超越期望的价值体验。
经过两年多的发展，客户数已经超过8.５万家 ，交易量超过1，060万吨 ，结算金额超过3００亿元 ，以其高度智能化的系统、专业可靠的服务走在了同行前列，目标在3年内成为全球第一的钢铁电商网站。
智慧平台，让钢铁交易更简单。
Shanghai Steel Trading Centre (SHGT.com) is a B2B steel e-business platform invested by Baosteel Group in 2013. As a leading company, we provide one-stop service including consulting, transaction, finance, metallic processing, logistics and so forth.
During the past year, we created more than 85,000 registered platform memberships. The annual business volume online is over 10.6 million tons; revenue is around 5 billion USD.
With our Intelligent Platform, you will have Simpler Business. OUYEEL!

**Comment by newmike** [comment]
孔令开会分别做30分钟的演讲；上海场的时间安排在上午！！！！
麻烦大妈给安排到上午吧~

**Comment by ZoomQuiet** [comment]
done 调整为第一个演讲了

On Fri, Sep 11, 2015 at 3:16 PM, Mike Zhang notifications@github.com
wrote:

> 孔令开会分别做30分钟的演讲；上海场的时间安排在上午！！！！
> 麻烦大妈给安排到上午吧~
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/103#issuecomment-139470390.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
