### ISSUE TITLE
[support]Gz: 社区合作 技术沙龙

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#107]
![](http://techparty.org/img/avatar.png)
# 简介

珠三角技术沙龙 - 打造泛珠三角技术圈线上线下交流的平台

珠三角技术沙龙以定期主办线下专业技术沙龙为特色，
在IT技术行业内享富盛名，以泛珠三角技术圈为核心，致力打造中国顶尖技术交流平台，
为广大程序猿、攻城狮、和技术爱好者量身定制。
沙龙定期会与各大技术社区合作，组织主办相关沙龙活动，
邀请技术行业和各大互联网公司一线大牛，
保证终身免费分享专业实用的行业经验和知识。
## 官网

http://techparty.org/
## 义务

全力支持 PyCon中国 广州场的各项事务

**Comment by newmike** [comment]
wow，很赞~
