### ISSUE TITLE
Update new two speaker information in PyCon2015 website

### ISSUE THREAD

**Issue by erizhang** [PyConChina/PyConCN#109]
There are new two guest speakers who has no introduction in the official web page: http://cn.pycon.org/2015/index.html , Could you please add them two on that page:
- **林曙勇**  测试架构师，新测试方法和技术的探索者和实践者，相信测试可以比我们现在大多数人认识的更有创造性
- **张裕** 诺基亚测试自动化教练

**Comment by ZoomQuiet** [comment]
信息不全哪
- 这两位是哪个城市演讲的?
- 哪个赞助公司的?
- 什么主题?
- 主题简介?
- 照片?

On Wed, Sep 9, 2015 at 10:27 AM, Eric Zhang notifications@github.com
wrote:

> There are new two guest speakers who has no introduction in the official
> web page: http://cn.pycon.org/2015/index.html , Could you please add them
> two on that page:
> - _林曙勇_ 测试架构师，新测试方法和技术的探索者和实践者，相信测试可以比我们现在大多数人认识的更有创造性
> - _张裕_ 诺基亚测试自动化教练
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/109.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by erizhang** [comment]
Updating:
- **林曙勇**《基于Robot Framework的通用协议测试框架介绍》，Robot Framework是使用Python实现的开源的测试自动化框架，在测试自动化领域应用十分广泛，演讲者将重点介绍其在通用通信协议测试中的应用介绍。演讲者是来自诺基亚的测试架构师，新测试方法和技术的探索者和实践者，相信测试可以比我们现在大多数人认识的更有创造性
- **张裕** 《也许是好的Python培训方式》，演讲者将介绍如何用Python的各种组件，搭起一个包含演示文稿，练习环境及测评的python培训环境。演讲者是来自诺基亚测试自动化教练。

Pictures are in: 链接：http://pan.baidu.com/s/1gAOsY 密码：0tvr
