### ISSUE TITLE
静态化输出的页面中存在英文显示

### ISSUE THREAD

**Issue by lxneng** [PyConChina/PyConCN#16]
如图， 有的地方显示了英文
![2014-07-15 11 28 52](https://cloud.githubusercontent.com/assets/112606/3586940/d16fc28a-0c34-11e4-946f-0db291b79819.png)

**Comment by limodou** [comment]
应该是以前有英文的翻译。我再看看怎么按中文来转换。

On Tue, Jul 15, 2014 at 11:29 PM, Eric Lo notifications@github.com wrote:

> 如图， 有的地方显示了英文
> [image: 2014-07-15 11 28 52]
> https://cloud.githubusercontent.com/assets/112606/3586940/d16fc28a-0c34-11e4-946f-0db291b79819.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/16.

## 

I like python!
UliPad <<The Python Editor>>: http://code.google.com/p/ulipad/
UliWeb <<simple web framework>>: https://github.com/limodou/uliweb
My Blog: http://my.oschina.net/limodou
