### ISSUE TITLE
显示小额赞助介绍信息

### ISSUE THREAD

**Issue by stingchen** [PyConChina/PyConCN#19]
需要在首页上显示小额赞助介绍信息，便于个人赞助。

**Comment by rothcold** [comment]
这个我来做。把PythonCN Group里面的内容放首页就可以了吧？

**Comment by stingchen** [comment]
也要注意布局，有些是按钮，然后链接到页面。

如“志愿者报名”，“讲师报名”应该是创建新页面，嵌入表单。

## 

Best Regards,

Sting Chen （陈世欣）

Gtalk: stingchen@gmail.com  QQ: 1025792036   Skype: *StingChen_ 微信：sting_xp
 *
 微博 http://weibo.com/stingchen 博客 http://sting.topgeek.org/ Linkedin
http://cn.linkedin.com/in/stingchen Google+
https://plus.google.com/114168404538613417248  |   TopGeek
http://topgeek.org/主席  |    PMCamp http://pmcamp.org/主席  |  上海谷歌开发者社区

## http://gdgshanghai.com/负责人 | 乐创园 http://lechuang.org/创始人

哲人无忧，智者常乐。并不是因为所爱的一切他都拥有了，而是所拥有的一切他都爱。

2014-07-23 17:44 GMT+08:00 Rothcold notifications@github.com:
