### ISSUE TITLE
发布PyCon大会志愿者招募信息表单

### ISSUE THREAD

**Issue by stingchen** [PyConChina/PyConCN#20]
PyCon2014大会志愿者申请表可以嵌入到官网的网页发布
在网页中以script的方式嵌入表单 （可以自适应高度，推荐使用）

```
<script 
    src='https://www.jinshuju.net/f/v7N6kL/embedded.js?banner=show&height=1483'
    ></script>
```

在网页中以iFrame的方式嵌入表单 （不能自适应高度，谨慎使用）

```
<iframe id='goldendata_form_v7N6kL' 
    src='https://www.jinshuju.net/f/v7N6kL?banner=show&embedded=true' width='100%' 
    frameborder=0 height='1483'>
    </iframe>
```

**Comment by ZoomQuiet** [comment]
2014-07-23 15:19 GMT+08:00 Sting Chen notifications@github.com:

> PyCon2014大会志愿者申请表可以嵌入到官网的网页发布
> 在网页中以script的方式嵌入表单 （可以自适应高度，推荐使用）

可有相关文档或是工具,自动生成我们已有申请表单的嵌入代码?

> 在网页中以iFrame的方式嵌入表单 （不能自适应高度，谨慎使用）
> 
> —
> Reply to this email directly or view it on GitHub.

## 

人生苦短, Pythonic! 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!
俺: http://zoomquiet.io
许: http://creativecommons.org/licenses/by-sa/2.5/cn/

**Comment by stingchen** [comment]
代码已经提交了，但是显示时候自动被隐藏了。

PyCon2014大会志愿者申请表可以嵌入到官网的网页发布
在网页中以script的方式嵌入表单 （可以自适应高度，推荐使用）

<script src='
https://www.jinshuju.net/f/v7N6kL/embedded.js?banner=show&height=1483
'></script>

在网页中以iFrame的方式嵌入表单 （不能自适应高度，谨慎使用）

<iframe id='goldendata_form_v7N6kL' src='
https://www.jinshuju.net/f/v7N6kL?banner=show&embedded=true' width='100%'
frameborder=0 height='1483'></iframe>

## 

Best Regards,

Sting Chen （陈世欣）

Gtalk: stingchen@gmail.com  QQ: 1025792036   Skype: *StingChen_ 微信：sting_xp
 *
 微博 http://weibo.com/stingchen 博客 http://sting.topgeek.org/ Linkedin
http://cn.linkedin.com/in/stingchen Google+
https://plus.google.com/114168404538613417248  |   TopGeek
http://topgeek.org/主席  |    PMCamp http://pmcamp.org/主席  |  上海谷歌开发者社区

## http://gdgshanghai.com/负责人 | 乐创园 http://lechuang.org/创始人

哲人无忧，智者常乐。并不是因为所爱的一切他都拥有了，而是所拥有的一切他都爱。

在 2014年7月23日 下午3:33，Zoom.Quiet notifications@github.com写道：

**Comment by ZoomQuiet** [comment]
嵌入在

http://cn.pycon.org/2014/proposals/
