### ISSUE TITLE
基于VPS 接口构建简单的流量控制工具

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#25]
## 背景
- 开始尝试为私人赞助提供 SS 服务,但是,所有VPS并没有流量控制能力
- [DigitalOcean API](https://developers.digitalocean.com/#reboot-a-droplet)
- [GetMonitor — QingCloud 文档](https://docs.qingcloud.com/api/monitor/get_monitor.html)
## 方案

通过合适的 API 构建简单的命令行工具:
1. 感知流量
2. 超过时报警
3. 自动或是人工重启
## 进展/讨论

这样好不好呢?

**Comment by lxneng** [comment]
好像没这个必要吧？ :smile:
