### ISSUE TITLE
动态/静态网站混合发布指定首页

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#26]
# 问题
- 以往网站都是用 UliWeb 动态发布的
- 今年尝试用 MkDocs 进行静态渲染发布

但是,网站的默许首页分布在不同系统中,
需要通过 Nginx 进行精巧的调配
# 分析

关键配置:

```
upstream pycon-frontends {
     server 127.0.0.1:5001;
}
...
location / {
    proxy_pass_header Server;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_pass http://pycon-frontends;
}
location ^~ /2014/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pyconcn.qiniudn.com;
    proxy_pass  http://pyconcn.qiniudn.com/2014/ ;
}
```
# 方案

最好能保持 UliWeb 的动态网站不变,
用其它形式,替换默认的 `/` 再跳转到 `/2014`

**Comment by ZoomQuiet** [comment]
简单的方法:
- 将原先UliWeb 的整体代理为 `/u`
- `/` 用一个静态网页替代,包含

```
    <meta http-equiv=“refresh” content=“0;URL=2014/“>
```

来跳转

**Comment by lxneng** [comment]
@ZoomQuiet 
2011, 2012, 2013用原来Uliweb版本
2014用http://pyconcn.qiniudn.com/2014/
对么？

**Comment by ZoomQuiet** [comment]
对的,就是这个思路

2014-08-06 15:47 GMT+08:00 Eric Lo notifications@github.com:

> @ZoomQuiet https://github.com/ZoomQuiet
> 2011, 2012, 2013用原来Uliweb版本
> 2014用http://pyconcn.qiniudn.com/2014/
> 对么？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/26#issuecomment-51303543.

## 

人生苦短, Pythonic! 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
俺: http://zoomquiet.io
许: http://creativecommons.org/licenses/by-sa/2.5/cn/

**Comment by lxneng** [comment]
好了， 我看你nginx已经配置过了， 只要pull一下最新的 `PyConCN`的code就可以了， 里面已经默认跳转到http://cn.pycon.org/2014/

**Comment by ZoomQuiet** [comment]
能给出对应的 commit 版本链接嘛?
没明白是怎么跳转的?
看起来是:
- 配置 UliWeb,令默许子应用为 `2014`
- 但是,本身没有现实 `2014`
- 利用 Nginx 的配置,完成 `2014` 的发布

?

**Comment by lxneng** [comment]
上次我做过一次`2014`的初始化 https://github.com/PyConChina/PyConCN/blob/master/apps/home/views.py

**Comment by ZoomQuiet** [comment]
got it
