### ISSUE TITLE
小额捐赠的个人贡献者墙

### ISSUE THREAD

**Issue by limodou** [PyConChina/PyConCN#3]
### 需求分析
- 显示个人捐献名单
### 设计
- 増加个人捐献表（用户id，捐献金额，活动ID）
### 数据库
- 个人捐献表(PersonSponsor)
### 问题
- 如果用户不是注册用户怎么办？

**Comment by Yuanye** [comment]
1.个人贡献者墙，要不要有头像？如果有是不是根据邮箱获取Gravatar头像？
2.“用户不是注册用户怎么办？” 是什么意思？ 这个表的数据不是后台添加的吗？

**Comment by limodou** [comment]
2012/8/26 MichaelGe notifications@github.com

> 1.个人贡献者墙，要不要有头像？如果有是不是根据邮箱获取Gravatar头像？
> 2.“用户不是注册用户怎么办？” 是什么意思？ 这个表的数据不是后台添加的吗？
> 
> 在 Uliweb中有一个auth
> app，我们将使用它进行用户管理。它是可以保存一个头像的。所以我们也可以让用户自行上传。当然Gravatar也可以，不过这块我的确没做过，如果感兴趣也可以用这种方式。不过简单的话，还是自已去管理比较方便。

捐献用户未必是注册用户，也可能是很多种方式来捐献的。所以我的意思是这样的用户，我们是存名字，还是存ID，存名字就无所谓是不是注册用户了。这块看
@stingchen 有什么建议？

## 

I like python!
UliPad <<The Python Editor>>: http://code.google.com/p/ulipad/
UliWeb <<simple web framework>>: https://github.com/limodou/uliweb
My Blog: http://my.oschina.net/limodou

**Comment by stingchen** [comment]
显示的名字，头像都可以用户自定义，还需要显示用户简介，和一些社会化信息，如微博，facebook，LinkedIn

## 

Best Regards,

Sting Chen （陈世欣）
微博: http://weibo.com/stingchen
博客: http://sting.topgeek.org
MSN: sxchen2k@hotmail.com
QQ: 1025792036
Gtalk：stingchen@gmail.com
Skype：stingchen_
Linkedin: http://cn.linkedin.com/in/stingchen
 http://cn.linkedin.com/in/stingchenGoogle+:
https://plus.google.com/114168404538613417248
Groups: TopGeek.org主席, PMCamp.org主席，上海谷歌开发者社区GDG负责人

---

哲人无忧，智者常乐。并不是因为所爱的一切他都拥有了，而是所拥有的一切他都爱。

在 2012年8月26日 下午9:44，limodou notifications@github.com写道：

**Comment by limodou** [comment]
2012/8/26 Sting Chen notifications@github.com

> 显示的名字，头像都可以用户自定义，还需要显示用户简介，和一些社会化信息，如微博，facebook，LinkedIn
> 
> 那这样的话，是不是可以认为我们自已来管理头像，并且捐献用户需要注册？

## 

I like python!
UliPad <<The Python Editor>>: http://code.google.com/p/ulipad/
UliWeb <<simple web framework>>: https://github.com/limodou/uliweb
My Blog: http://my.oschina.net/limodou

**Comment by stingchen** [comment]
无需注册，我们来管理。因为我们知道谁捐献了。

## 

Best Regards,

Sting Chen （陈世欣）
微博: http://weibo.com/stingchen
博客: http://sting.topgeek.org
MSN: sxchen2k@hotmail.com
QQ: 1025792036
Gtalk：stingchen@gmail.com
Skype：stingchen_
Linkedin: http://cn.linkedin.com/in/stingchen
 http://cn.linkedin.com/in/stingchenGoogle+:
https://plus.google.com/114168404538613417248
Groups: TopGeek.org主席, PMCamp.org主席，上海谷歌开发者社区GDG负责人

---

哲人无忧，智者常乐。并不是因为所爱的一切他都拥有了，而是所拥有的一切他都爱。

在 2012年8月26日 下午9:54，limodou notifications@github.com写道：

**Comment by limodou** [comment]
2012/8/26 Sting Chen notifications@github.com

> 无需注册，我们来管理。因为我们知道谁捐献了。
> 
> 那么是不是捐献用户和一般的用户是分开管理？他们的信息基本一致，但是分开存放，并且捐献用户是由我们来创建。

但同时带来问题，如果捐献用户本身已经注册，是不是我们还要重复录入。如果我们已经录入了捐献用户，结果这个用户又注册了，那么又如何处理？还有头像是谁传上去的？如果是我们维护的，是不是由我们来上传的？

也许简单的做法是注册用户和捐献用户分别管理，信息允许，可以定现一定的数据同步（如用户和捐献用户都存在时，以用户为准同步捐献用户中的信息，数据冗余存放）

## 

I like python!
UliPad <<The Python Editor>>: http://code.google.com/p/ulipad/
UliWeb <<simple web framework>>: https://github.com/limodou/uliweb
My Blog: http://my.oschina.net/limodou

**Comment by stingchen** [comment]
分开管理吧。

目前捐赠者很少，不会造成很大的维护量和数据冗余。

## 

Best Regards,

Sting Chen （陈世欣）
微博: http://weibo.com/stingchen
博客: http://sting.topgeek.org
MSN: sxchen2k@hotmail.com
QQ: 1025792036
Gtalk：stingchen@gmail.com
Skype：stingchen_
Linkedin: http://cn.linkedin.com/in/stingchen
 http://cn.linkedin.com/in/stingchenGoogle+:
https://plus.google.com/114168404538613417248
Groups: TopGeek.org主席, PMCamp.org主席，上海谷歌开发者社区GDG负责人

---

哲人无忧，智者常乐。并不是因为所爱的一切他都拥有了，而是所拥有的一切他都爱。

在 2012年8月26日 下午10:00，limodou notifications@github.com写道：

**Comment by limodou** [comment]
2012/8/26 Sting Chen notifications@github.com

> 分开管理吧。
> 
> 目前捐赠者很少，不会造成很大的维护量和数据冗余。
> 
> 那我们就先定下吧：注册用户和捐献用户分别管理。捐献用户由我们来管理。头像管理放在uliweb中。数据同步等以后再说。

## 

I like python!
UliPad <<The Python Editor>>: http://code.google.com/p/ulipad/
UliWeb <<simple web framework>>: https://github.com/limodou/uliweb
My Blog: http://my.oschina.net/limodou
