### ISSUE TITLE
2014 静态化网站兼容问题

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#30]
关联: #28 #35 
# 现象
- http://cn.pycon.org/2014 正确
- 但是,子页面异常:
  - http://cn.pycon.org/sponsors.html
  - 应该是:
    - http://cn.pycon.org/2014/sponsors.html
# 分析
- 原先静态生成时,统一为根是 `http://cn.pycon.org/`
# 方案
- 重新生成一下 2014 的所有内容
- 调整前导为 `http://cn.pycon.org/2014/`
- 同时,为了明年的兼容:
  - 将 2015 的也预先定义为:
  - `http://cn.pycon.org/2015`
  - 使用 Nginx 进行统一重定向

**Comment by 7c00** [comment]
2014 网站生成的页面没有使用绝对路径的，都是相对路径，应该是nginx的配置问题

**Comment by ZoomQuiet** [comment]
server {
    listen 80;
    server_name cn.pycon.org;

```
access_log /var/log/nginx/cn.pycon.org.access.log;
error_log /var/log/nginx/cn.pycon.org.error.log;

#rewrite ^/2014/?(.*?)$ /$1? permanent;
#rewrite ^/(201[123].*)$ /uli/$1? permanent;
rewrite ^/2015/?(.*?)$ /$1? permanent;

location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pyconcn.qiniudn.com;
    proxy_pass  http://pyconcn.qiniudn.com/2015/ ;
    expires off;
}

location /2014 {
    #alias /opt/www/PyConChina/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pyconcn.qiniudn.com;
    proxy_pass  http://pyconcn.qiniudn.com/2014/ ;
    expires off;
}

location ^~ /static/ {
    #alias /opt/www/PyConChina/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pychina.qiniudn.com;
    proxy_pass  http://pychina.qiniudn.com/uli/static/ ;
    expires off;
}

location /2013/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pychina.qiniudn.com;
    proxy_pass  http://pychina.qiniudn.com/uli/2013/ ;
    expires off;
}
location /uli/2013/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pychina.qiniudn.com;
    proxy_pass  http://pychina.qiniudn.com/uli/2013/ ;
    expires off;
}
location /2012 {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pychina.qiniudn.com;
    proxy_pass  http://pychina.qiniudn.com/uli/2012/ ;
    expires off;
}
location /uli/2012 {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pychina.qiniudn.com;
    proxy_pass  http://pychina.qiniudn.com/uli/2012/ ;
    expires off;
}
location /2011 {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pychina.qiniudn.com;
    proxy_pass  http://pychina.qiniudn.com/uli/2011/ ;
    expires off;
}
location /uli/2011 {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host pychina.qiniudn.com;
    proxy_pass  http://pychina.qiniudn.com/uli/2011/ ;
    expires off;
}

# location / {
#     #   141016 upgrade as default;
#     proxy_pass_header Server;
#     proxy_redirect off;
#     proxy_set_header Host $http_host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Scheme $scheme;
#     proxy_pass http://pycon-statics;
# }

#location /uli {
#    #   141016 move into /uli
#    proxy_pass_header Server;
#    proxy_redirect off;
#    proxy_set_header Host $http_host;
#    proxy_set_header X-Real-IP $remote_addr;
#    proxy_set_header X-Scheme $scheme;
#    proxy_pass http://pycon-frontends;
#}

#location ^~ /static/ {
#    alias /opt/app/PyConCN_Uli/static/;
#}

location = /robots.txt{
    log_not_found off;
}

location = /favicon.ico{
    log_not_found off;
}
```

}

**Comment by 7c00** [comment]
`location /2014`  改 `location /2014/`？

**Comment by ZoomQuiet** [comment]
其实,这种配置是可以本地测试的吧,
都是反向代理而已,,,

2015-07-14 10:58 GMT+08:00 Todd Gao notifications@github.com:

> location /2014 { 改 location /2014/？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/30#issuecomment-121117480.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by 7c00** [comment]
嗯， 我在本地按照 `location /2014/` 的配置是可以正常访问的，`location /2014` 会出现和官网一样的问题。

**Comment by 7c00** [comment]
解决方案已经给出，没人处理？

**Comment by ZoomQuiet** [comment]
没忙过来,,,,
主机权限都有谁有的?!
这个也应该协同起来哪.

2015-07-20 11:24 GMT+08:00 Todd Gao notifications@github.com:

> 解决方案已经给出，没人处理？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/30#issuecomment-122746247.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by chencoyote** [comment]
目前这个工作组里面的人是都没有主机权限的

**Comment by ZoomQuiet** [comment]
嚓! 不应该哪,
推举个半夜能起来解决问题的,
俺来帮忙部署 ssh 密匙!

2015-07-20 11:56 GMT+08:00 5unny notifications@github.com:

> 目前这个工作组里面的人是都没有主机权限的
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/30#issuecomment-122753305.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by xen0n** [comment]
啊, 我现在不能在凌晨工作了... 不过偶尔的话应该可以? 我这段时间一般在0点前后休息

我的ssh公钥:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPeLXvIHHUassadIguRpVtPNxoQ6/GnOvZiTqViEUDouWP4d6qj2E9tbRZYeUptDuoM6JbZrQ9fSltj0wVwVp2f+rDKW+WQqO0mAVByUahZjwthLnTzSMA6TZZA+Y6sMJRfm3gld9PGnFeGL7h6xRRxkDBkWd/9rDQXqmbqA6q83qYf+AqRyo2vcK9TZ0nYFAU1u99U4+xwuuQvPozn4yfjuKif1/Z9TDJxHyBPTsKbQWISOCy3XNF/21mENEb4NxJ1a99wxNQ8mnrMgOVCamFBSLEPt8ZRE0icniuWaeLM91JiPRTnId/6uNNfBXN3DLBBBvFjQJ8rwpq0EgciqEiPEMqiAk7wvb29S261negxUXs4x1PhoupCtCy5DxCT9S6vPwNR+rsnGR38n4WESJKRyjMsH0Z3QrByb0i1GTdY1V3V2hYDp4xTnGh90a9gKCBz6EyyQtzEjmObfJCvDPdkhALnG9wYotH6vai+vp1qZi7Io5hpXHV13Y295Y/+1BCPasNcPWtP5idA6QUlm1ROlMLHQqt1j9e/wU5mQzUu8khZZT5Gpke4V5Ho4OyvuZpOSTCFfbszdnrRPgR+yZeS+vnbWYNnj9UdcvU9h5QAwKbThrh1nk2En7LGwxbYctr/LJyp7ox4zqlP+ZeTkEwkDA/CMM4vU1lBeo8Hun77w== idontknw.wang+pycon@gmail.com
```

**Comment by ZoomQuiet** [comment]
完成部署 ;-)
进入后共同维护
/opt/cfg/scmlogging.md
就好 ;-)

通过 hg 进行远程配置管理,
部署有 hg /hooks 嘦从本地成功 hg push ,
远程对应配置文件就能更新,
所以,建议从本地编辑配置文件,
远程进行进程重启,观察

以免以往在远程完成了修订,忘记入库,
以至配置丢失...

在 2015年7月21日 下午5:12，Wang Xuerui notifications@github.com 写道：

> 啊, 我现在不能在凌晨工作了... 不过偶尔的话应该可以? 我这段时间一般在0点前后休息
> 
> 我的ssh公钥:
> 
> ssh-rsa
> AAAAB3NzaC1yc2EAAAADAQABAAACAQDPeLXvIHHUassadIguRpVtPNxoQ6/GnOvZiTqViEUDouWP4d6qj2E9tbRZYeUptDuoM6JbZrQ9fSltj0wVwVp2f+rDKW+WQqO0mAVByUahZjwthLnTzSMA6TZZA+Y6sMJRfm3gld9PGnFeGL7h6xRRxkDBkWd/9rDQXqmbqA6q83qYf+AqRyo2vcK9TZ0nYFAU1u99U4+xwuuQvPozn4yfjuKif1/Z9TDJxHyBPTsKbQWISOCy3XNF/21mENEb4NxJ1a99wxNQ8mnrMgOVCamFBSLEPt8ZRE0icniuWaeLM91JiPRTnId/6uNNfBXN3DLBBBvFjQJ8rwpq0EgciqEiPEMqiAk7wvb29S261negxUXs4x1PhoupCtCy5DxCT9S6vPwNR+rsnGR38n4WESJKRyjMsH0Z3QrByb0i1GTdY1V3V2hYDp4xTnGh90a9gKCBz6EyyQtzEjmObfJCvDPdkhALnG9wYotH6vai+vp1qZi7Io5hpXHV13Y295Y/+1BCPasNcPWtP5idA6QUlm1ROlMLHQqt1j9e/wU5mQzUu8khZZT5Gpke4V5Ho4OyvuZpOSTCFfbszdnrRPgR+yZeS+vnbWYNnj9UdcvU9h5QAwKbThrh1nk2En7LGwxbYctr/LJyp7ox4zqlP+ZeTkEwkDA/CMM4vU1lBeo8Hun77w==
> idontknw.wang+pycon@gmail.com
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by xen0n** [comment]
本线索中的补丁已经部署, 实测有效, 各位看下没问题就close吧
