### ISSUE TITLE
报名入口开放条件

### ISSUE THREAD

**Issue by chencoyote** [PyConChina/PyConCN#31]
### 并发条件

报名签到入口的确定 #27
### 必要条件
- 议题明确 51%
- 赞助明确 60%
### 充分条件
- [ ] 会议举办时间
- [ ] 会议举办地点
  -  [x] 城市: 北京, 上海, 珠海, 苏州, 杭州 
  -  [ ] 详细地址
- [ ] 主办方联系方式
- [ ] 票价
  - [ ] 免费票(需审核)
  - [ ] 收费票分类
### 附加条件

多城市举办是否各城市分开报名, 还是统一报名
- 分开报名: 创建多个活动页面
- ~~统一报名~~
  -  ~~创建多个售票类型(北京-免费票)~~
  -  ~~统一命名, 根据实际签到地点区分~~

如果确认以上信息, 报名入口即可开放

**Comment by ZoomQuiet** [comment]
必要条件满足才能有足够的信息来决策充分条件

另外,报名肯定是分开报名的,不存在联票性质....

**Comment by chencoyote** [comment]
已经被否定, 故删除
- ~~统一报名~~
  -  ~~创建多个售票类型(北京-免费票)~~
  -  ~~统一命名, 根据实际签到地点区分~~
