### ISSUE TITLE
迁移staticpycon到github

### ISSUE THREAD

**Issue by 7c00** [PyConChina/PyConCN#32]
为了统一工作平台，将把GitCafe上的
[staticpycon项目仓库](https://gitcafe.com/PyConChina/staticpycon/)迁移到Github上来，以后将：
- **只**提交代码到Github新仓库
- **只**接受Github上的新仓库的issue和pull request
- 原GitCafe上的仓库, 作为备份仓库,自动化同步

需要依次完成下面的工作:
- [x] 仓库迁移：
  - [x] 在Github PyConChina之下创建 staticpycon 仓库
  - [x] 导入原仓库的代码(全部版本)
  - [ ] 原仓库简介和README增加说明和链接指向新仓库
  - [x] ~~停用原仓库工单和pull request功能~~(GitCafe不支持该功能)
  - [x] _（optional, 手工）导入原仓库的工单到新仓库的issues中_
- [ ] 部署变更：
  - [ ] 升级 fabric 脚本,从本地基于 github 对 7niu 空间进行自动化部署
  - [ ] _（optional）利用社区多个主机空间,形成网站冗灾发布集群_
- [ ] 仓库协作：
  - [ ] 编写服务器端脚本（或采用其他方式），定期pull新仓库再push到原仓库
  - [ ] _（optional, 手工）不定期 push 最新代码到 gitcafe 仓库_

**Comment by ZoomQuiet** [comment]
每个子任务,其实都应该对应一个具体的 Issue 来追踪的,
或是简单的,每完成一个,应该在这儿评注一个 commit log 链接,来证明完成.

**Comment by ZoomQuiet** [comment]
完成了没有? 进展呢?!
应该及时在这儿以及 wx 中通告哪,,,
当然的列表也是必须有的,,,

**Comment by 7c00** [comment]
仓库迁移基本完成，剩余_简介修改_没有权限，等其他人认领

_部署变更_和_仓库协作_，涉及服务器权限，考虑从这个issue中删去，新开两个issue（并关联到这个issue）

**Comment by ZoomQuiet** [comment]
sure ;-)
