### ISSUE TITLE
[PUB]99元捐赠PyChina社区及PyCon2015大会

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#33]
# 背景

PyCon2012China 开始,就设立了特别的私人赞助机制
# 方案

去年 PyCon2014China 一结束,就创立了对应表单:

嵌入式代码:

```
<script 
    src='https://jinshuju.net/f/jMnL83/embedded.js?banner=show&background=white&height=1269'>
</script>
```
## 提示

参考去年的单独页面嵌入 html 代码的形式

**Comment by ZoomQuiet** [comment]
[e22ae602](https://gitcafe.com/PyConChina/staticpycon/commit/e22ae60257f39396b6f44dd81e417ee13bfb6e83)

谁给合并到 github 这儿来?!

**Comment by 7c00** [comment]
@ZoomQuiet 已经迁移到github，怎么还在gitcafe提交代码

**Comment by ZoomQuiet** [comment]
俺没有等到你的迁移手册哪,,,
只能继续惯性使用了,,,,

所以,约定个时间点?
俺将 gitcafe 的仓库关闭?!

现在先进行版本合并一下!?

你来?

也记录到 README 吧...

2015-07-09 14:55 GMT+08:00 Todd Gao notifications@github.com:

> @ZoomQuiet https://github.com/ZoomQuiet 已经迁移到github，怎么还在gitcafe提交代码
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/33#issuecomment-119846011.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by 7c00** [comment]
代码已同步到 github ，更新了README 上的相关链接 https://github.com/PyConChina/staticpycon/commit/e22ae60257f39396b6f44dd81e417ee13bfb6e83

**Comment by 7c00** [comment]
是否合并 master 和 2015 分支？

**Comment by ZoomQuiet** [comment]
2015-07-09 20:51 GMT+08:00 Todd Gao notifications@github.com:

> 是否合并 master 和 2015 分支？

必须的哪,否则,其它人无法简单的切换的哪,,,

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by ZoomQuiet** [comment]
42 小时戳...

2015-07-09 23:01 GMT+08:00 Zoom.Quiet zoom.quiet@gmail.com:

> 2015-07-09 20:51 GMT+08:00 Todd Gao notifications@github.com:
> 
> > 是否合并 master 和 2015 分支？
> 
> 必须的哪,否则,其它人无法简单的切换的哪,,,
> 
> ## 
> 
> Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
> 俺: http://zoomquiet.io
> 授: http://creativecommons.org/licenses/by-sa/2.5/cn/
> 怒: 冗余不做,日子甭过!备份不做,十恶不赦!
> KM keep growing environment culture which promoting organization be learnning!

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by 7c00** [comment]
我现在开始合并分支，稍侯

**Comment by 7c00** [comment]
@ZoomQuiet 

原2015分支已经合并到master， 2015分支已经删除，以后的修改在 master分支上进行；
新建b2014分支作为对2014年数据的备份，考虑到以后可能会有数据修改用了branch而非tag；

**Comment by ZoomQuiet** [comment]
好的;
哪么期望大家如何在本地完成切换?!

给个完备的指导性说明哪...

在 2015年7月12日 下午12:35，Todd Gao notifications@github.com写道：

> @ZoomQuiet https://github.com/ZoomQuiet
> 
> 原2015分支已经合并到master， 2015分支已经删除，以后的修改在 master分支上进行；
> 新建b2014分支作为对2014年数据的备份，考虑到以后可能会有数据修改用了branch而非tag；
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/33#issuecomment-120686616.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by 7c00** [comment]
本地代码只需要修改 remote 地址即可，这是 最基本 git 操作，还需要写说明？

```
git remote set-url origin git@github.com:PyConChina/staticpycon.git
# 同步到最新代码
git pull 
```

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)
知道不知道是别人的能力
说不说是我们的素质了...

文档的完备度是项目的认真度哪...

2015-07-12 17:23 GMT+08:00 Todd Gao notifications@github.com:

> 本地代码只需要修改 remote 地址即可，这是 最基本 git 操作，还需要写说明？
> 
> git remote set-url origin git@github.com:PyConChina/staticpycon.git
> 
> # 同步到最新代码
> 
> git pull
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/33#issuecomment-120703118.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by ZoomQuiet** [comment]
是否,所有涉及到的志愿者都切换过来了?!
俺删除 gitcafe 的仓库可以?!

在 2015年7月12日 下午11:48，Zoom.Quiet zoom.quiet@gmail.com写道：

> 是也乎,(￣▽￣)
> 知道不知道是别人的能力
> 说不说是我们的素质了...
> 
> 文档的完备度是项目的认真度哪...
> 
> 2015-07-12 17:23 GMT+08:00 Todd Gao notifications@github.com:
> 
> > 本地代码只需要修改 remote 地址即可，这是 最基本 git 操作，还需要写说明？
> > 
> > git remote set-url origin git@github.com:PyConChina/staticpycon.git
> > 
> > # 同步到最新代码
> > 
> > git pull
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/PyConChina/PyConCN/issues/33#issuecomment-120703118.
> 
> ## 
> 
> Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
> 俺: http://zoomquiet.io
> 授: http://creativecommons.org/licenses/by-sa/2.5/cn/
> 怒: 冗余不做,日子甭过!备份不做,十恶不赦!
> KM keep growing environment culture which promoting organization be
> learnning!

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by chencoyote** [comment]
留着吧, 做备份用呗, 万一.......
