### ISSUE TITLE
[文案]演讲主题召集

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#34]
- 背景: 9.12/13/18 三城市日期已决定
- 分析: 按照大会筹备进程,7月应该完成主要议题的明确
- 决议: 7.10 前,完成基础文案,在各种渠道中发布:
  - 官方 blog
  - CPyUG 列表
  - 相关城市 微信群
  - 官方 weibo
  - eDM
  - ...
- 内容:
  - 今年口号: ?
  - 内容范畴: 老12项
    - [Pycon Asia Pacific](http://devrel.zoomquiet.io/data/20111109180644/index.html)
    - 往年文案: [PyCon中国过往参与者倡议信_v140909_v2](https://docs.google.com/document/d/1AHmU9IXzPK8g49wUB_5wzti6D75-zQhJgtPN5P1cBvI/edit)
  - 申报地址: http://cn.pycon.org/proposals.html
# 文案
## 正文:

PyCon2015China 大会将在今年程序员节日前后举行!
(9.12/上海;9.13/广州;9.19/北京;)

过往四届,总是有对分享主题不够干货的报怨,所以,今年大会将强化议题评审.
提前两个月公开征集议题,分享一年来的 Pythonic 体验;

特此倡议:
1. 如果你认同 PyCon中国大会 的精神,请向你的小伙伴宣传我们的官网:
   http://cn.pycon.org/
   关注大会举行情况,及时报名再次就近参加 ;-)
2. 如果近年你有足以自得的 Py 相关体验请向大会提交主题/工作坊:
   http://cn.pycon.org/proposals.html

PS:
附以往的行者心声::
做为一个技术从业者,在这种类型的会议上想听到下面的一些内容,就以python为例来说吧,这也符合任专业性的技术论坛:
1.  python现阶段的应用方向,以及python的发行版之间的功能差别,新的发行版的亮点.
2.  python在某个行业的应用的场景及相关的需求及技术分析,如果以取得成功的应用来分析,估计很多人会兴奋.
3.  python在实际应用中,如何与其它现有的非python的项目去协同工作.
4. python本身的开源社区如何交互,现有哪些经典的python开源代码,如何与与开源代码的维护者一起互动,或者贡献自己的力量.
5. python比较成熟的开源项目的应用分析,移植难点,以及它的协议(GPL or BSD,
   other?)是否扯上法务相关的事物,这个论题会帮助解决将python开源项目商业化时碰到的各种问题.

PPS:

官方建议的话题,在这些方面,但不限于此:
- Core Python and other implementations: ?IronPython, Jython, PyPy and
  Stackless. Python核心或是其它实现
- Python in Education, Science and Math Python 在教育/科研/数学领域
- Python libraries and extensions Python 库或是扩展
- Business Applications 商业应用
- Databases 数据库
- Embedding and Extending Python 嵌入或是扩展Python
- Game Programming 游戏开发
- GUI Programming 图形用户界面开发
- Network Programming 网络开发
- Python in IT Security Python 在IT安全
- Open Source Python projects 开源Python 项目
- Packaging Issues 发行探讨
- Programming Tools 开发工具
- Project Best Practices 项目最佳体验
- System Administration 系统管理
- Web Programming (Django, Zope, TurboGears, WSGI) Web开发

大会资源:
- 官网: http://cn.pycon.org
- 列表: pyconchinese@googlegroups.com
- 邮箱: support@pychina.org
- weibo:    http://weibo.com/pyconcn
- wechat:   PyChinaOrg

**Comment by chencoyote** [comment]
文案调整建议

# PyCon2015中国大会主题召集.

## 正文

一年一度的PyCon2015即将召开, 目前已经有3座城市举办时间已定:
- 9.12 @上海;
- 9.13 @广州;
- 9.19 @北京;

过往四届,总是有对分享主题不够干货的报怨. 所以,今年大会将**强化议题评审.**
提前两个月公开征集议题,分享一年来的 Pythonic 体验.
- 2015年, 互联网+, 大数据, 云计算.. Python无处不在, 最佳实践成功案例却鲜为人知,
- 2015年, 年度最具争议的话题Python2 还是Python3? Python3到底是不是毁掉了Python?
- 2015年, 虚拟现实, 人工智能火遍全球, Python从中起到什么作用?
- 当然, 还有官方建议话题参考 [附录1]()
- 其他与Python有关的主题, 想法, 创意

如果你对上述话题有足矣自得的见解, 当然最好符合从业者的心声 [附录2](), 请向大会提交主题/工作坊:
- 栽培: 2015.8.15 23:32
- 官网: [http://cn.pycon.org/proposals.html](http://cn.pycon.org/proposals.html)
- 邮箱: support@pychina.org

## 特此倡议

如果你认同 PyCon中国大会的精神,
如果你对PyCon中国大会充满期待
如果你关注Python或者你的企业正在使用Python
如果你想面基你心目中的Pythoneer
如果你是一个Pythoner
如果还有如果....

请你和你的小伙伴们, 共同关注大会举行情况, 及时报名, 就近参加, 同时向更多的人宣传我们  ;-)
- 官网: [http://cn.pycon.org/](http://cn.pycon.org/)
- 列表: [pyconchinese@googlegroups.com](pyconchinese@googlegroups.com)
- 邮箱: [support@pychina.org](support@pychina.org)
- weibo: [http://weibo.com/pyconcn](http://weibo.com/pyconcn)
- wechat: PyChinaOrg

## 附录1 -- 官方建议话题
- Core Python and other implementations: ?IronPython, Jython, PyPy and Stackless. Python核心或是其它实现
- Python in Education, Science and Math Python 在教育/科研/数学领域
- Python libraries and extensions Python 库或是扩展
- Business Applications 商业应用
- Databases 数据库
- Embedding and Extending Python 嵌入或是扩展Python
- Game Programming 游戏开发
- GUI Programming 图形用户界面开发
- Network Programming 网络开发
- Python in IT Security Python 在IT安全
- Open Source Python projects 开源Python 项目
- Packaging Issues 发行探讨
- Programming Tools 开发工具
- Project Best Practices 项目最佳体验
- System Administration 系统管理
- Web Programming (Django, Zope, TurboGears, WSGI) Web开发

## 附录2 -- 从业者的心声

做为一个技术从业者,在这种类型的会议上想听到下面的一些内容,就以python为例来说吧,这也符合任专业性的技术论坛:
1. python现阶段的应用方向,以及python的发行版之间的功能差别,新的发行版的亮点.
2. python在某个行业的应用的场景及相关的需求及技术分析,如果以取得成功的应用来分析,估计很多人会兴奋.
3. python在实际应用中,如何与其它现有的非python的项目去协同工作.
4. python本身的开源社区如何交互,现有哪些经典的python开源代码,如何与与开源代码的维护者一起互动,或者贡献自己的力量.
5. python比较成熟的开源项目的应用分析,移植难点,以及它的协议(GPL or BSD, other?)是否扯上法务相关的事物,这个论题会帮助解决将python开源项目商业化时碰到的各种问题.

**Comment by ZoomQuiet** [comment]
已经列表发布! 并发布在 简书:
[PyCon2015中国大会主题 开始召集! - 简书](http://www.jianshu.com/p/b906fae0cce0)

可以进行其它传播了,,,

**Comment by chencoyote** [comment]
[PyCon2015中国大会主题 开始召集! - v2ex](http://v2ex.com/t/205513)
[PyCon2015中国大会主题 开始召集! - 微信公众号PyChinaOrg](http://mp.weixin.qq.com/s?__biz=MzA4ODIzMDkyNQ==&mid=208226853&idx=1&sn=e59a508d038d60e3736328e6bf2fa457&key=c76941211a49ab58c0f4e78a79e8c96007e0927a2b3ca8293cabf580e50b53ce87fff6c2c789032e542fec5fefb1e29e&ascene=1&uin=MTE1MjEzNjU%3D&devicetype=Windows+7&version=61020020&pass_ticket=VRZKwO32JPqZuU0LJzvrXJEbw2c7wtXB7EoCDrVBedo%3D)

**Comment by chencoyote** [comment]
qq群消息发布 ![qq群消息发布](https://cloud.githubusercontent.com/assets/6293606/8664646/7e19ff14-2a0c-11e5-9fc0-9eb54b6ea9ae.png)

微信群, 朋友圈转发 get√

**Comment by ZoomQuiet** [comment]
点赞!

在 2015年7月14日 上午9:30，5unny notifications@github.com写道：

> PyCon2015中国大会主题 开始召集! - v2ex http://v2ex.com/t/205513
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/34#issuecomment-121106547.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by chencoyote** [comment]
[PyCon2015中国大会主题 开始召集! - 微信公众号PyChinaOrg](http://mp.weixin.qq.com/s?__biz=MzA4ODIzMDkyNQ==&mid=208226853&idx=1&sn=e59a508d038d60e3736328e6bf2fa457&key=c76941211a49ab58c0f4e78a79e8c96007e0927a2b3ca8293cabf580e50b53ce87fff6c2c789032e542fec5fefb1e29e&ascene=1&uin=MTE1MjEzNjU%3D&devicetype=Windows+7&version=61020020&pass_ticket=VRZKwO32JPqZuU0LJzvrXJEbw2c7wtXB7EoCDrVBedo%3D)
