### ISSUE TITLE
[提议] 创建 pyconchina.github.io 项目仓库

### ISSUE THREAD

**Issue by 7c00** [PyConChina/PyConCN#35]
PyCon China 2011到2014年大会的网站都已经静态化，预计今后也会继续使用静态化网站，为此提议创建 pyconchina.github.io 项目仓库。这样可以：
1. 更好地利用 Github Pages 功能；
2. 发布页面（HTML）和生成工具（staticpycon）分离，易于维护；
3. 把 staticpycon 项目的 [staticuliweb](https://github.com/PyConChina/staticpycon/tree/staticuliweb) 分支分离出来，使得项目本身更紧凑；

为此，需要讨论下面的问题：
1. 这个提议是否值得实施；
2. 如果实施，需要考虑的问题，比如 文件目录结构、路径约定、网页发布流程等。

请各位在这条issue下回复意见或建议。

**Comment by ZoomQuiet** [comment]
在 2015年7月9日 下午8:06，Todd Gao notifications@github.com写道：

> ...提议创建 pyconcn.github.io 项目仓库。这样可以：
> 
> ...
> 
> 这个提议是否值得实施；
- 从 cn.pycon.org 网站的主要目标人群看
- 不值当...github-pages 的解析速度/和谐可能性...
- 无法长期使用,为大陆读者

> 如果实施，需要考虑的问题，比如 文件目录结构、路径约定、网页发布流程等。
- 将工具/网站分离,这个目标是合理的
- 可以将 PyConCn.github.io 作为 cn.pycon.org 的备份来使用
- 目录为:

https://github.com/PyConChina/PyConCn.github.io.git

```
+- 2015
|   +- static
+- 2014
|   +- static
+- 2013
|   +- static
+- 2012
|   +- static
+- 2011
|   +- static
\- index.html   ~ 整体说明, 可以包含自动跳转到当年的 JS 代码
```

相同结构数据也应该部署在:
- http://pyconcn.qiniudn.com/
- 社区 SS 服务器0/1/2/3

这样就可以通过 Nginx 部署为多上游网站,进行并行发送

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by ZoomQuiet** [comment]
关联: 迁移staticpycon到github · Issue #32

## 资源汇总

当前 PyConChina 相关的所有网站资源:
- group: [PyConChina - GitCafe](https://gitcafe.com/PyConChina)
  - 2014 官网重构 MkDoc 原型[PyConChina/MkDoc4PyCon - GitCafe](https://gitcafe.com/PyConChina/MkDoc4PyCon)
  - (已迁移为 [staticpycon](https://github.com/PyConChina/staticpycon))原创静态化工具: [PyConChina/staticpycon - GitCafe](https://gitcafe.com/PyConChina/staticpycon)
  - gitcafe-pages 容器仓库 [PyConChina/PyConChina - GitCafe](https://gitcafe.com/PyConChina/PyConChina)
- group: [PyConChina - github](https://github.com/PyConChina)
  - 2011~13 uliweb 版本官网[PyConChina/PyConCN](https://github.com/PyConChina/PyConCN)
  - 2014/15 静态官网 [PyConChina/staticpycon](https://github.com/PyConChina/staticpycon)
  - H5抽奖工具 [PyConChina/lucky](https://github.com/PyConChina/lucky)
- hosts:
  - Linode(东京): 
    - 别名: `OBP`
    - ip: 106.187.97.72
    - cn.pycon.org 域名绑定
    - 官网 nginx 发布/反代理
  - DigitalOcean(SFO): SS1/SS2/SS3
    - SSD 硬盘小主机
    - 作为静态网站均衡上游主机群
- Bucket 7niu:
  - http://pyconcn.qiniudn.com/
    - 2014/
    - 2015/
    - 静态发布空间
  - http://pychina.qiniudn.com/
    - uli/2013/
    - uli/2012/
    - uli/2011/
    - UliWeb 静态化发布空间

## 重整规划
- `OBP` 主机ip 不可变更 (cn.pycon.org 的域名解析在 PyCon 官方)
- 一致化各种发布空间的结构
- 一致性发布历史以及未来所有 PyConChian 官网
- 尽可能多的部署冗余空间:
  - gitcafe-pages
  - github-pages
  - 7牛 CDN
  - 自有主机
- 通过 fabric/ansible 部署脚本,自动化所有空间的发布
