### ISSUE TITLE
 官网内容结构重构

### ISSUE THREAD

**Issue by 7c00** [PyConChina/PyConCN#36]
迁移自 https://gitcafe.com/PyConChina/staticpycon/tickets/16
            https://gitcafe.com/PyConChina/staticpycon/tickets/15

原issue内容 ：

[titckets/16] 官网内容结构重构

> ## 背景
> - 参考: 工单 #15: [style]PyCon 2014 in Montréal · PyConChina/staticpycon - GitCafe
> - 我们当前的大会官网,内容极其简陋,根本无法给有兴趣的人提供足够的消息
> ## 分析
> 
> 从来没有认真规划过!
> 
> 方案
> - 抄之!
> - 先从人家的 E文 内容进行整体复制
> - 然后对应翻译为中文文案!
> - 发布方案同 stlye 的,,,

[titckets15] [style]PyCon 2014 in Montréal

> ## 现象
> 
> PyCon2011China 是 Limodu 独立完成的官网,
> 结果一路惯性下来,
> 到今年,才进行了两次尝试,
> 依然没有整体感觉
> ## 分析
> - 没有专门进行整体设计
> - 强行使用兼容排版来考虑
> ## 建议
> - 抄是最快的出路!
> - PyCon 2014 in Montréal 非常清新
> - 建议直接复制过来再针对汉字进行微调!
>   -先分支一个 static2015pycon ,
> - 发布为:
>   - http://cn.pycon.org/2015 进行整理
>   - 明年 2/14,就切换为 http://cn.pycon.org/ 正式启用!

**Comment by ZoomQuiet** [comment]
坚定的可以!
先发布一个分支, 测试一下

在 2015年7月14日 下午2:07，Todd Gao notifications@github.com写道：

> 迁移自 https://gitcafe.com/PyConChina/staticpycon/tickets/16
> https://gitcafe.com/PyConChina/staticpycon/tickets/15
> 
> 原issue内容 ：
> 
> [titckets/16] 官网内容结构重构
> 
> ##背景
> - 参考: 工单 #15 https://github.com/PyConChina/PyConCN/pull/15:
>   [style]PyCon 2014 in Montréal · PyConChina/staticpycon - GitCafe
> - 我们当前的大会官网,内容极其简陋,根本无法给有兴趣的人提供足够的消息
> 
> ##分析
> 从来没有认真规划过!
> 
> 方案
> - 抄之!
> - 先从人家的 E文 内容进行整体复制
> - 然后对应翻译为中文文案!
> - 发布方案同 stlye 的,,,
>   
>   [titckets15] [style]PyCon 2014 in Montréal
> 
> ##现象
> PyCon2011China 是 Limodu 独立完成的官网,
> 结果一路惯性下来,
> 到今年,才进行了两次尝试,
> 依然没有整体感觉
> 
> ##分析
> - 没有专门进行整体设计
> - 强行使用兼容排版来考虑
> 
> ##建议
> - 抄是最快的出路!
> - PyCon 2014 in Montréal 非常清新
> - 建议直接复制过来再针对汉字进行微调! -先分支一个 static2015pycon ,
> - 发布为:
>   - http://cn.pycon.org/2015 进行整理
>   - 明年 2/14,就切换为 http://cn.pycon.org/ 正式启用!
>   
>   —
>   Reply to this email directly or view it on GitHub
>   https://github.com/PyConChina/PyConCN/issues/36.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by ZoomQuiet** [comment]
可用进展?!

**Comment by 7c00** [comment]
这个issue只是迁移原来 GitCafe 的工单

**Comment by ZoomQuiet** [comment]
迁移的就是值得作的哪....
要是感觉来不及可以先关闭

2015-07-22 16:49 GMT+08:00 Todd Gao notifications@github.com:

> 这个issue只是迁移原来 GitCafe 的工单
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/36#issuecomment-123622258.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
