### ISSUE TITLE
[staticpycon]JSON 数据输出

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#38]
## 背景

[PyCon2015China 专用 app. · Issue #37 · PyConChina/PyConCN](https://github.com/PyConChina/PyConCN/issues/37)
## 分析
- 官网静态化后,其实,我们应该有更多渠道可复合输出
- 以 yaml 为格式的信息整理,有利于人工协同
- 但是,作为 app 或是其它自动化输出
  - JSON 包含结构
  - 通用
  - 可压缩
## 方案

改进当前静态化编译工具
同时输出一个完整的 sitemapp 式的全部数据 .json

**Comment by 7c00** [comment]
生成json比较容易，添加几行代码就行，但首先需要确定生成数据的格式和内容

**Comment by ZoomQuiet** [comment]
这个,尽可能和自然的网站结构配置起来,
为了给 web app 生成网页用的,
从这个角度考虑,
先生成一版,可以进行内部调试就好.

输出的文件就是 cnpycon.josn 吧

2015-07-20 11:22 GMT+08:00 Todd Gao notifications@github.com:

> 生成json比较容易，添加几行代码就行，但首先需要确定生成数据的格式和内容
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/38#issuecomment-122746059.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by 7c00** [comment]
partially done

https://github.com/PyConChina/staticpycon/commit/cdee65b0e95ae9145f8a793750fcca16ffe144ff
