### ISSUE TITLE
[speech]Bj: 杜军

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#50]
# 杜军

~ 北京锐和信首席后台扫地僧
## Python 与 智能硬件

我们用 python 写了 lapsule 的大部分逻辑，包括 sso  , api , portal 以及与node.js的融合， lapsule 是一个专注于智能音箱垂直领域的云端服务，包括内容整合，设备OTA 升级支持，数据统计，数据分析，移动端研发支持等整体解决方案，我们为用户提供硬件核心模块，云端内容服务，app定制，驻厂工程师支持，交钥匙方案
## TODO
- 明确真实内容...

**Comment by newmike** [comment]
今天与他电话沟通后，他说可能没时间参加了，这次演讲就放弃了~~~~

**Comment by ZoomQuiet** [comment]
好的! 俺从议程中调整出去...

On Sat, Sep 5, 2015 at 9:21 PM, Mike Zhang notifications@github.com wrote:

> 今天与他电话沟通后，他说可能没时间参加了，这次演讲就放弃了~~~~
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/50#issuecomment-137955664.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
