### ISSUE TITLE
[speech]Bj: 黄鑫

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#51]
# 黄鑫

~ FreeWheel资深devops一枚，做得最多的是监控和部署发布。Pythonist，目前正在从Golang挖墙脚，有点痴迷。
## 基于Fabric的自动化实践

"讲解Fabric在企业自动化中的具体应用。常规任务的自动化，与Shell的交互以及其实现原理，基于SSH的安全通信。作为部署解决方案的实现，与多个代码源、Jenkins、代理前端交互实现一体化部署，执行完操作后基本检测，生成报表并提供结构化数据用于事后分析。
- Fabric原理
- 常见自动化任务
- 部署方案集成
- 使用中的一些问题"

**Comment by chifeng** [comment]
已经跟黄鑫沟通，可以按时参加，内容小有变化，需要更新上来。

**Comment by ZoomQuiet** [comment]
照片还是没有给哪,,,
这也是需要及时协同收集的

On Wed, Sep 2, 2015 at 4:36 PM, Chifeng notifications@github.com wrote:

> 已经跟黄鑫沟通，可以按时参加，内容小有变化，需要更新上来。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/51#issuecomment-136976413.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by dreampuf** [comment]
抱歉，头像在此。
![image](https://cloud.githubusercontent.com/assets/353644/9627918/129510b6-519a-11e5-922e-93a547f9bb31.png)

内容稍后更新。
