### ISSUE TITLE
[speech]Bj: 丁来强 高并发函数式编程

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#54]
# 丁来强

~ 从业十年, Splunk(美国纳斯达克第一家纯大数据的上市公司)在中国实验室的Tech Lead, 负责大数据平台相关的ETL和数据可视化相关的工作. 技术兴趣广泛. 擅长C++/Python与JS.
# 使用Python进行高并发函数式编程

~ (Using Python to do parallel functional programming with high order functions and libraries)

"不同于面向对象编程的函数式编程以其低副作用, 高并发性获得极大关注与发展(e.g. Scala, Hashell, Erlang等). Python并不是纯粹的函数式编程语言, 但是提供了极其强大的语言特性使得进行函数式编程的可能. 
本主题涵盖函数式编程在Python的关键点实现, 覆盖Python核心语法(function, lambda, generator, iterator, decorator等)和相关标准库(functools, operators, itertools)外, 主要通过一个实例介绍如何使用多个高阶函数与库(multipledispatch, pyrsistent, fn, PyToolz, more-itertools等)进行多并发的函数式编程."

**Comment by wjo1212** [comment]
这个议题资料已经递交, 标题和描述可能要修改一下, 还请更新一下. 多谢!

使用Python进行高效函数式编程

 (Effective python functional programming: techniques, tools and practices)

介绍:

不同于面向对象编程的函数式编程以其低副作用, 高模块复用性与易并发性获得极大关注与发展(e.g. Scala, Hashell, Erlang等). Python并不是纯粹的函数式编程语言, 但是提供了极其强大的语言特性使得进行函数式编程的可能. 

本主题涵盖函数式编程的各种重要特性在Python的关键点实现, 覆盖Python核心语法(function, lambda, generator, iterator, decorator等)和相关标准库(functools, operators, itertools)外, 涉及到函数式编程的核心思想, 技术(pure function, persistent data, high order function, currying, TCO, trampoline, overloading, pattern matching, laziness streaming等), 工具(multipledispatch, pyrsistent, fn, PyToolz, ipython cluster, python-parallel, 等)以及并发相关的编程, 进行有效的函数式编程.

**Comment by ZoomQuiet** [comment]
已经更新到官网,
多谢哉!

2015-08-21 7:46 GMT+08:00 LaiQiang Ding notifications@github.com:

> 这个议题资料已经递交, 标题和描述可能要修改一下, 还请更新一下. 多谢!
> 
> 使用Python进行高效函数式编程
> 
> (Effective python functional programming: techniques, tools and practices)
> 
> 介绍:
> 
> 不同于面向对象编程的函数式编程以其低副作用, 高模块复用性与易并发性获得极大关注与发展(e.g. Scala, Hashell, Erlang等).
> Python并不是纯粹的函数式编程语言, 但是提供了极其强大的语言特性使得进行函数式编程的可能.
> 
> 本主题涵盖函数式编程的各种重要特性在Python的关键点实现, 覆盖Python核心语法(function, lambda, generator,
> iterator, decorator等)和相关标准库(functools, operators, itertools)外,
> 涉及到函数式编程的核心思想, 技术(pure function, persistent data, high order function,
> currying, TCO, trampoline, overloading, pattern matching, laziness
> streaming等), 工具(multipledispatch, pyrsistent, fn, PyToolz, ipython cluster,
> python-parallel, 等)以及并发相关的编程, 进行有效的函数式编程.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/54#issuecomment-133212691.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
