### ISSUE TITLE
[speech]Sh: 丁来强 高效大数据分析处理与可视化

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#55]
# 丁来强

~ 从业十年, Splunk(美国纳斯达克第一家纯大数据的上市公司)在中国实验室的Tech Lead, 负责大数据平台相关的ETL和数据可视化相关的工作. 技术兴趣广泛. 擅长C++/Python与JS.
# 使用Python进行高效大数据分析处理与可视化

~ Big Data Processing and Virtualisation for Analysis using Python 
- 介绍:
  大数据处理中, 70%左右的时间我们在做处理准备(加载, 抽取, 清洗, 转换, 分组, 合并等), 进行商务分析的过程中(以及之后), 又会花相当多的时间做数据可视化的工作. 这个主题覆盖多个流行数据处理可视化的工具与一些最佳实践的经验.
- 概述:
  大数据处理中, 70%左右的时间我们在做处理准备(加载, 抽取, 清洗, 转换, 分组, 合并等), 进行商务分析的过程中(以及之后), 又会花相当多的时间做数据可视化的工作. 这个主题介绍了如何使用Python选择高效的数据处理分析与可视化. 
  内容结合一个实际例子覆盖了如何使用Pandas进行高效数据ETL, Pandas的最新特性(Query, 去GIL等), BokeH如何进行高效数据可视化. Blaze与Spark结合进行更大规模的分布式数据处理等. "

**Comment by wjo1212** [comment]
Hi 大妈,
Sorry, Folk没找到修改地方, 还方便帮忙改一下介绍么 (主要给北京场的)? 多谢!

大数据处理中;70%左右的时间我们在做处理准备(加载/抽取/清洗/转换/分组/ 合并等); 进行商务分析的过程中(以及之后);又会花相当多的时间做数据可视化的工作. 这个主题介绍了如何使用Python选择高效的数据处理分析与可视化.内容通过多个实例, 覆盖了如何使用Pandas进行高效数据ETL与分析; 使用SeaBorn与BokeH进行高效数据可视化; 使用Blaze与Spark与Pandas结合进行更大规模的数据分析与可视化等.

**Comment by ZoomQuiet** [comment]
fixed ;-)

北京你将连续两场演讲?!
辛苦了...

2015-09-16 11:22 GMT+08:00 LaiQiang Ding notifications@github.com:

> Hi 大妈,
> Sorry, Folk没找到修改地方, 还方便帮忙改一下介绍么 (主要给北京场的)? 多谢!
> 
> 大数据处理中;70%左右的时间我们在做处理准备(加载/抽取/清洗/转换/分组/ 合并等);
> 进行商务分析的过程中(以及之后);又会花相当多的时间做数据可视化的工作.
> 这个主题介绍了如何使用Python选择高效的数据处理分析与可视化.内容通过多个实例, 覆盖了如何使用Pandas进行高效数据ETL与分析;
> 使用SeaBorn与BokeH进行高效数据可视化; 使用Blaze与Spark与Pandas结合进行更大规模的数据分析与可视化等.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/55#issuecomment-140614887.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by wjo1212** [comment]
嗯呐, 感谢!
