### ISSUE TITLE
[speech]Gz: 潘俊勇 QT

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#56]
# 潘俊勇

~ 易开发(cloud.easydo.cn)创始人，国内最早的Python开发者之一，现在专注构建企业应用快速开发平台。
## 使用QT/gevent打造跨平台的端服务

和phonegap的移动端跨平台开发原理类似，端服务让web开发者可以访问更多桌面原生功能，比如桌面提醒、断点上传、断点下载、文件同步等。你不再需要为各个浏览器写插件，使用Python来写端服务扩展即可！更可轻松自动支持windows、mac、linux多终端！我们使用了QT、gevent等技术来实现，主题将介绍产品架构、多端打包方法，以及碰到的一些坑。

**Comment by panjunyong** [comment]
这个主题，我们就不提供了，因为精力有限，这次专注到mqtt，下次pycon再讲qt.

**Comment by ZoomQuiet** [comment]
got it

**Comment by JokerQyou** [comment]
虽然讲得不是很好，还是来露一下脸 :crying_cat_face: 之前网络 ID 从没曝光过
