### ISSUE TITLE
[speech]Gz: 多栖全栈 邱文武

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#57]
![jokerqyou](https://cloud.githubusercontent.com/assets/22494/9251331/37d2aeb4-4205-11e5-99c4-b06ead7b6206.png)
# 潘俊勇

~ 易开发(cloud.easydo.cn)创始人，国内最早的Python开发者之一，现在专注构建企业应用快速开发平台。
## 使用MQTT打造类Slack的实时消息服务

已成为标准的MQTT提供了QoS的消息代理服务，解决了实时系统高并发的问题。易开发的消息服务利用了MQTT、Socket.io、ElasticeSearch等技术，实现单聊、私聊、通知、扩展服务等功能，并提供桌面提醒功能，即将和微信企业号整合。主题将在MQTT服务器选型、服务端产品架构、插件编写、客户端架构、多端聊天状态同步等多方面进行介绍。

**Comment by panjunyong** [comment]
这个主题，我们就不提供了，因为精力有限，专注到mqtt，下次pycon再讲

**Comment by panjunyong** [comment]
这个主题，我们让我公司 邱文武 来露脸一下：

邱文武 在 易开发 被誉为多栖全栈开发工程师，根据开发需要游走于系统后端、多平台桌面、web前端，负责公司 消息系统前后端 以及 端服务的开发，业余爱好折腾开源软件。
