### ISSUE TITLE
[speech]Sh: 王立奇

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#58]
# 王立奇

~ 上海仪酷智能科技有限公司产品经理，VIRobotics创始人。在机器人应用开发、Linux、Python、NI图形化软件开发方面有着丰富的经验。
## 图形化python—快速构建机器人系统
- 1.发布公司旗舰软件产品：Python机器人NAO基于NI LabVIEW的开发包。
- 2.介绍利用LabVIEW调用Python模块，并开发机器人应用程序的方法。
- 3.介绍利用VIRobotics软件产品将NI LabVIEW与Python交叉编译的方式。
- 4.介绍利用开发包添加Python模块的方式。

**Comment by newmike** [comment]
嘉宾照片还没有，速度解决啊~

**Comment by wangstoudamire** [comment]
怎么上传啊？

**Comment by ZoomQuiet** [comment]
嗯哼,好象评注的不给上传的?!
那就直接邮件我们也成 ;-)

On Sun, Aug 30, 2015 at 8:09 PM, wangstoudamire notifications@github.com
wrote:

> 怎么上传啊？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/58#issuecomment-136131335.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
