### ISSUE TITLE
[speech]Sh: 陈海波

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#60]
# 陈海波

~在Python与桌面软件编程上，有比较多的涉猎。
http://zrey.com/home
## Python&GUI

国内貌似对于Python&GUI上能直接看到的资料，基本停留于Hello World的阶段，没有梳理过，但内容应该会有下面这些：
- Why GUI
- 基本技术路线的选择
- 不同平台上的编译、打包软件
- 界面怎么绘制？
  - layout的概念
  - 善用styles
- 没有真正意义上的跨平台银弹
  - ICON
  - 画阴影
  - 文本渲染机制的重写
- 嵌入Flask等本地Web服务
- 嵌入个Mongodb（第三方软件），何尝不可？
- 如何快速地为软件制作网站
- 软件的授权码、购买流程如何处理
- 场景的不一致性（内存）
- 版权上的问题
- 如何制作软件的宣传视频
- 自动化
- GUI赋予的想象力
- 如何开始你的第一个桌面软件？

**Comment by hepochen** [comment]
![screen shot 2015-08-15 at 10 56 30 pm](https://cloud.githubusercontent.com/assets/396846/9289411/2bab3b7c-43a1-11e5-830b-4874186f443c.jpg)

**Comment by ZoomQuiet** [comment]
fot got ;-)

On Sat, Aug 15, 2015 at 10:59 PM, hepochen notifications@github.com wrote:

> [image: screen shot 2015-08-15 at 10 56 30 pm]
> https://cloud.githubusercontent.com/assets/396846/9289411/2bab3b7c-43a1-11e5-830b-4874186f443c.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/60#issuecomment-131390538.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by newmike** [comment]
海波的公司及职位信息有吗？还有个人详细介绍，放出来，我好更新到宣传渠道啊~

**Comment by hepochen** [comment]
@newmike  公司是我自己的，还没打算公开，不好意思。 个人介绍，可以简单的说，比如FarBox的创始人，知道的人相对多一些。 :)

另外，我不是很清楚，现在的日程已经定下来了吗？

如果是安排在闪电演讲，可能要麻烦你们帮我取消这次的topic，这个时间我自己要安排在其它事情上了，非常抱歉。

**Comment by ZoomQuiet** [comment]
日程没有明确,
哪个时段,多长时间, 对你的行程方便呢?

**Comment by ZoomQuiet** [comment]
三城日程统筹 · Issue #62 · PyConChina/PyConCN 
    https://github.com/PyConChina/PyConCN/issues/62

调整到 15:40 是否可以?

**Comment by hepochen** [comment]
好的。
