### ISSUE TITLE
[sign-in]报名入口31会议发布页面

### ISSUE THREAD

**Issue by chencoyote** [PyConChina/PyConCN#61]
关联 #31 
## 入口
- 北京: http://event.31huiyi.com/118591776 或者 http://pycon2015beijing.31huiyi.com
- 广州: http://event.31huiyi.com/118545334 或者 http://pycon2015guangzhou.31huiyi.com
- 上海: http://event.31huiyi.com/118022165  或者  http://pycon2015shanghai.31huiyi.com
## 查错

由于每一个地区会议发布为一个活动, 所以会造成信息不同步, 请各位double check!!
问题统一反馈至此, 统一进行增补

北京场提供测试票:  http://event.31huiyi.com/112981767     可以购买测试票, 对报名流程进行测试.
## 完善
- [ ] 题图美化
- [ ] 会议地址确认
  - [ ] 北京举办会议地址
  - [ ] 上海举办会议地址
- [ ] 票量确认(当前统一为: 学生票:200 蟒人票:100 普通票: 400)
  - [ ] 北京票量:
  - [ ] 广州票量
  - [ ] 上海票量

**Comment by newmike** [comment]
上海报名入口改为：http://event.31huiyi.com/118022165
也可以点击：http://pycon2015shanghai.31huiyi.com

**Comment by chencoyote** [comment]
@newmike  赞~  北京和广州可以通过31会议的复制功能来创建
![image](https://cloud.githubusercontent.com/assets/6293606/9325463/1a051a2a-45c5-11e5-945d-89607ea53c7c.png)

**Comment by newmike** [comment]
广州场报名入口改为：http://event.31huiyi.com/118545334
也可以点击：http://pycon2015guangzhou.31huiyi.com

**Comment by newmike** [comment]
北京场报名入口改为：http://event.31huiyi.com/118591776
也可以点击：http://pycon2015beijing.31huiyi.com

**Comment by ZoomQuiet** [comment]
已发布: [e7b1a56](https://github.com/PyConChina/staticpycon/commit/e7b1a5625bcb477e33160f18355a3ccafa5d6352)
