### ISSUE TITLE
[speech]Sh: 肖凯

### ISSUE THREAD

**Issue by xccds** [PyConChina/PyConCN#66]
### 肖凯
- 工作：1号店商务智能部数据挖掘工程师
- 个人：喜欢折腾点数据，喜欢用不同的工具和方法来折腾数据，当然也包括python。
- 题目：python中的数据工具箱
- 概述：介绍近年来python社区涌现的一些数据分析工具，包括numpy/scipy/pandas/sklearn/theano等等。还会介绍这些工具箱在数据分析工作流程中的位置，以及和其它类似工具的比较。

![mylinkedin](https://cloud.githubusercontent.com/assets/1450275/9709291/9694bcb2-555b-11e5-9e47-58fb616b4a00.jpg)

**Comment by ZoomQuiet** [comment]
照片也请及时提供哪 ;-)

2015-08-14 15:31 GMT+08:00 xccds notifications@github.com:

> 肖凯
> - 工作：1号店商务智能部数据挖掘工程师
> - 个人：喜欢折腾点数据，喜欢用不同的工具和方法来折腾数据，当然也包括python。
> - 题目：python中的数据工具箱
>   -
>   概述：介绍近年来python社区涌现的一些数据处理工具，包括numpy/scipy/pandas/sklearn/theano等等。还会介绍这些工具箱在数据分析工作流程中的位置，以及和其它类似工具的比较。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/66.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
