### ISSUE TITLE
[speech]Sh:shell909090 一种远程执行代码的方法

### ISSUE THREAD

**Issue by shell909090** [PyConChina/PyConCN#68]
10分钟的小演讲，介绍一种将任何代码扔去远程执行的小技巧。

**Comment by ZoomQuiet** [comment]
照片呢!
没有俺就用上次那个 demo 了,,,,

On Mon, Aug 17, 2015 at 2:35 PM, Shell.Xu notifications@github.com wrote:

> 10分钟的小演讲，介绍一种将任何代码扔去远程执行的小技巧。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/68.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by ZoomQuiet** [comment]
不对,还有自个儿的自述呢...

On Mon, Aug 17, 2015 at 2:48 PM, Zoom.Quiet zoom.quiet@gmail.com wrote:

> 照片呢!
> 没有俺就用上次那个 demo 了,,,,
> 
> On Mon, Aug 17, 2015 at 2:35 PM, Shell.Xu notifications@github.com
> wrote:
> 
> > 10分钟的小演讲，介绍一种将任何代码扔去远程执行的小技巧。
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/PyConChina/PyConCN/issues/68.
> 
> ## 
> 
> Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
> 俺: http://zoomquiet.io
> 授: http://creativecommons.org/licenses/by-sa/2.5/cn/
> 怒: 冗余不做,日子甭过!备份不做,十恶不赦!
> KM keep growing environment culture which promoting organization be
> learnning!

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by shell909090** [comment]
去年的吧。大妈，这都好多年了。。。

**Comment by shell909090** [comment]
啥时候slide deadline？我要赶快了。前几天会议保证工作花了太多时间。

**Comment by ZoomQuiet** [comment]
其实 deadline 是 8.21 哪,,,
不过,老蠎们,可以迟一点儿,
尽快吧, 反正能增补的

On Wed, Sep 2, 2015 at 3:12 PM, Shell.Xu notifications@github.com wrote:

> 啥时候slide deadline？我要赶快了。前几天会议保证工作花了太多时间。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/68#issuecomment-136958048.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
