### ISSUE TITLE
[speech]:TW 亮亮(王亮博)

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#72]
# liang2

**Comment by ccwang002** [comment]
我会分享在 Pinkoi 公司使用 jieba 处理中文断词、结合公开数据（wiki、字典）word2vec 公司应用经验（商品智能分类、搜寻优化），最后再提一点台湾 Python 社群 (PyCon TW) 近况。

9/12 上海场时间即可，可照大会安排 13、19 号场次亦可。照片与完整大纲周末补上

**Comment by ccwang002** [comment]
演講內容（抱歉遲了一陣）

## Abstract 摘要

首先分享在 Pinkoi 實習的經驗，如何使用 jieba 與改善 Elasticsearch 中文商品搜尋體驗，同時分享調整 jieba 斷詞於搜尋使用的一些經驗。再進一步透過 word2vec 自動找出商品間的關係，利用它語意上的特徵，完成一些如相似商品推薦等進階的搜尋功能。剩下的時間將會介紹現階段台灣 Python 社群發展以及宣傳明年活動。

## About the Speaker 講者介紹

亮亮目前就讀台灣大學生醫電資碩士，研究領域為癌症基因調控網路分析。平時經常參與台灣開源社群如 Taipei.py 與 MLDM Monday (Taiwan R User) 活動，於 PyCon APAC 2014、2015 擔任工作人員與講者，同時亦為 PyCon TW 2016 議程組長。去年於北京 Microsoft Asia Research (MSRA) 實習，現於台灣電子商務公司 Pinkoi 實習。
- 個人網站：http://liang2.tw
- @ccwang002

**Comment by ccwang002** [comment]
頭像

![img_0644](https://cloud.githubusercontent.com/assets/1544283/9498633/5725bfac-4c4d-11e5-8ded-7fcf11233bdd.jpg)

**Comment by newmike** [comment]
所以这是一个在线演讲咯？ 我们用什么工具进行链接？

**Comment by ccwang002** [comment]
去年是用 Google Hangout，主要看你们方便的工具，我都可以先测试。

**Comment by ZoomQuiet** [comment]
必须使用 Hangout ! 因为 TW 的网络是开放的, Hangout 是美好的,直通 Youtube 的

**Comment by taiyun** [comment]
帅气！

**Comment by ccwang002** [comment]
我 9/4、5（六日）、9/9（五） 都可测试 Hangout

**Comment by newmike** [comment]
个人建议用那个Skype，不需要翻墙，不会有网速的问题。。。

**Comment by newmike** [comment]
之前GDG的几次会，用Hangout经常卡顿

**Comment by ccwang002** [comment]
今天与大妈测试了 Hangout 以及 Skype 都没有问题，预计会参加 9/12、13 上海、广州两场。谢谢！

**Comment by ccwang002** [comment]
hi 我把投影片连结放在 http://blog.liang2.tw/2015Talk-Chinese-Search/pycon_cn_shanghai.html
现在还在修改中，可能开场前再跟会众们公布。到时候他们有问题想问我，可以直接在 twitter 上 ping 我 （@ccwang002），问答的时候我会看那个，就不担心视讯效果不好

**Comment by ZoomQuiet** [comment]
好的!

2015-09-12 10:24 GMT+08:00 Liang Bo Wang notifications@github.com:

> hi 我把投影片连结放在
> http://blog.liang2.tw/2015Talk-Chinese-Search/pycon_cn_shanghai.html
> 现在还在修改中，可能开场前再跟会众们公布。到时候他们有问题想问我，可以直接在 twitter 上 ping 我 （@ccwang002
> https://github.com/ccwang002），问答的时候我会看那个，就不担心视讯效果不好
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/72#issuecomment-139703165.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by ccwang002** [comment]
@ZoomQuiet 大妈迅速！看到讲义上官网了感谢！

ps 广州应该会是另一个网址：http://blog.liang2.tw/2015Talk-Chinese-Search/pycon_cn_guangzhou.html

**Comment by ZoomQuiet** [comment]
嗯哼,临时先给两个讲义链接,大家猜...
只是,广州现场的网络是否能支持稳定的直播不知道,
最好今天上海的演讲,你直接录制发布到 youtube 晚上俺下载到本地,
万一不行,留个后手...

On Sat, Sep 12, 2015 at 11:28 AM, Liang Bo Wang notifications@github.com
wrote:

> @ZoomQuiet https://github.com/ZoomQuiet 大妈迅速！看到讲义上官网了感谢！
> 
> ps 广州应该会是另一个网址：
> http://blog.liang2.tw/2015Talk-Chinese-Search/pycon_cn_guangzhou.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/72#issuecomment-139706066.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by ccwang002** [comment]
结果还是断线了，真是抱歉。视频录制已经发布到 youtube 了：https://youtu.be/KCeqTaJC0U8

**Comment by ZoomQuiet** [comment]
好的,明天一早拿到 UC 内部 wifi 口令后,
俺就测试一下网络,
实在不行就只有果断录播了...

2015-09-12 14:49 GMT+08:00 Liang Bo Wang notifications@github.com:

> 结果还是断线了，真是抱歉。视频录制已经发布到 youtube 了：https://youtu.be/KCeqTaJC0U8
> 根据经验转档要个一小时左右，三点半再来刷也许就有了。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/72#issuecomment-139734104.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by newmike** [comment]
话说广州最后怎么处理的？ 今年上海又被吐槽了~

**Comment by ccwang002** [comment]
最后用 Skype，虽然中间断线了一次，但品质还行

**Comment by newmike** [comment]
嗯，那就好~~ 还是SKYPE靠谱啊，完全被HANGOUTS坑了。。。。

**Comment by ZoomQuiet** [comment]
非常非常 happy 的结果!

thanx for all!
