### ISSUE TITLE
[speech]:Gz Jeff

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#75]
# Jeff

~ 厚建广州创始人兼副总;珠三角技术沙龙常务组委. 长年活跃在一线的python码农.

**Comment by jeffkit** [comment]
长链接实时消息编程的门槛不低，长链接代理服务器可以有效地降低开发者开发实时应用的准入门槛，包括客户端及服务端，在服务端，开发者甚至可以使用HTTP的方式来实现业务逻辑的接入。本主题介绍如何使用Tornado实现一个分布式可扩展的长链接代理服务器。

**Comment by ZoomQuiet** [comment]
为什么选择了 Tornado 而不是其它的框架?!
