### ISSUE TITLE
[speech]Sh+Gz: 高驰涛(云智慧)

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#76]
# 高驰涛

高驰涛(Neeke)，云智慧高级架构师，是PHP开发组成员，同时也是PECL/SeasLog的作者.10年研发管理经验，早期从事大规模企业信息化研发架构，09年涉足互联网数字营销领域并深入研究架构与性能优化。2014年加入云智慧，致力于APM产品的架构与研发。崇尚敏捷，高效，GettingReal。
![3 pic](https://cloud.githubusercontent.com/assets/22494/9327389/087e72e8-45d3-11e5-9918-b57693d7bc39.jpg)

**Comment by newmike** [comment]
嘉宾主题什么时候能给？

**Comment by newmike** [comment]
他的主题：  让Python应用快如闪电-python应用性能管理实践

**Comment by ZoomQuiet** [comment]
fixed

继续等待主题简述

On Thu, Aug 27, 2015 at 10:41 AM, Mike Zhang notifications@github.com
wrote:

> 他的主题： 让Python应用快如闪电-python应用性能管理实践
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/76#issuecomment-135262418.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by ZoomQuiet** [comment]
个人简介：

刘国强（Bruce Liu）云智慧技术中心(Technical Center)副总裁，全面负责公司的售前、售后、技术咨询和培训方面的工作。在加入云智慧之前，他拥有超过18年的IT行业研发，IT管理，服务器和桌面虚拟架构，数据库和云计算专家，企业级方案专家。历任CA大中华区CTO，售前技术总监。Citrix中国区首席专家顾问，虚拟化系统工程师。在银行，电信，邮政和政府行业服务多年，是资深的行业IT、云计算和应用性能解决方案专家。

主题：Python应用的性能优化实践

如何能够追踪和定位Python应用的程序代码性能？使用云智慧的应用性能平台能够快速定位和发现Python应用的性能瓶颈，并找到有问题的代码。使用云智慧的APM ，您可以深入到运行在实际生产环境中的Python应用程序，从交易级了解Python程序堆栈跟踪诊断性能瓶颈。可以自动检测商业交易，了解响应时间、每分钟调用时间，深入到代码级的诊断显示完整的调用图和执行代码，同时了解到Python调用SQL语句的执行性能。在本次演讲中将我们将分析PythonCode如何插入Python解释器，并采集Python代码堆栈、资源利用情况、代码的错误异常数据等，最终让开发人员和业务人员能够在最短时间内发现问题，降低对业务的影响。
