### ISSUE TITLE
[speech]Gz: 林伟

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#78]
# 林伟

神级程序猿

**Comment by newmike** [comment]
嘉宾公司职位介绍，还没有吗？

**Comment by ZoomQuiet** [comment]
这儿没有就得直接向讲师沟通索取,
在这儿是资源汇集不是需求汇集...

On Mon, Aug 24, 2015 at 11:16 PM, Mike Zhang notifications@github.com
wrote:

> 嘉宾公司职位介绍，还没有吗？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/78#issuecomment-134244513.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
