### ISSUE TITLE
[翻译]讲师和赞助商信息

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#79]
## 问题
- [staticpycon/_sponsors.yaml at master · PyConChina/staticpycon ](https://github.com/PyConChina/staticpycon/blob/master/src/data/_sponsors.yaml)
- [staticpycon/_speakers.yaml at master · PyConChina/staticpycon ](https://github.com/PyConChina/staticpycon/blob/master/src/data/_speakers.yaml)
- 都为双语网站保留有 E 文字段
- 但是,大家的 Cnglish 都是二把刀,就别说 English 了
## 方案
- 从社区中邀请 E 文专业的
- 在此 Issue 中逐段翻译
- 当然,能进行 PR 更加好
## 行动

前述问题中是两个 `ymal` 数据文本,其中所有中文信息字段都需要有对应翻译
比如说:
- intro: "SegmentFault 是中国领先的开发者社区. 经过两年多年的发展,已经聚集了十多万开发者. 我们的目标是为中文开发者提供一个最纯粹的技术交流平台,一起创造属于开发者的时代!"
- 的对应E文翻译就是:
  - intro_en: "SegmentFault is China's leading developer community. After more than two years of development, SegmentFault is already have more than ten developer. SegmentFault's goal is to provide Chinese developers to one of the most pure technical exchange platform,  create belong to the age of developers together"

所以,需要对没有翻译的字段进行及时翻译
建议翻译过程:
- 打开两个目标文本: [_sponsors.yaml](https://github.com/PyConChina/staticpycon/blob/master/src/data/_sponsors.yaml)/[_speakers.yaml](https://github.com/PyConChina/staticpycon/blob/master/src/data/_speakers.yaml)
- 选择一段未翻译的中文信息,将字段名也一同复制下来,
  - 类似: 
  - intro: "美团云是美团推出的公有云平台，致力于为千万用户提供最稳定、可靠、高效的基础设施云服务以及大数据解决方案。2013年5月，美团云正式对外开放计算资源。此后，美团云依靠强大的技术团队，不断优化产品，注重用户体验、提供最优的底层架构以及稳定的网络服务。目前已服务众多企业级用户，行业覆盖O2O生活服务提供商、在线教育、知名电商、互联网金融、游戏、智能硬件、新媒体、汽车等。"
- 然后,在当前 Issue 的底部评论中粘贴入文本
- 同时在评论中完成这段信息的翻译
- 最后提交评注
- 然后一条评注,一个翻译,直至完成全部翻译

注意:
- 原始信息也在持续增补中
- 要注意评论的回复,有时,会有对应讨论和原文增补
## 进展
- 150821 增补具体行为建议
- 150819 大妈 强邀 今年大会纪念 TEE 书法创作大狮专业进行!

**Comment by ZoomQuiet** [comment]
- intro: "美团云是美团推出的公有云平台，致力于为千万用户提供最稳定、可靠、高效的基础设施云服务以及大数据解决方案。2013年5月，美团云正式对外开放计算资源。此后，美团云依靠强大的技术团队，不断优化产品，注重用户体验、提供最优的底层架构以及稳定的网络服务。目前已服务众多企业级用户，行业覆盖O2O生活服务提供商、在线教育、知名电商、互联网金融、游戏、智能硬件、新媒体、汽车等。"
- intro_en: "meituan cloud is the meituan group launched a public cloud platform, is committed to providing the most stable, reliable and efficient infrastructure cloud services and big data solutions to millions of users; in May 2013, the meituan cloud officially open computing resources. After that, the meituan cloud rely on a strong technical team, and constantly optimize the product, focusing on user experience, providing the best of the underlying architecture and stable network services has been serving many enterprise users, industry coverage O2O living ISP, online education, well-known electrical, Internet banking, gaming, intelligent hardware, new media, automotive and other. "

**Comment by haosdent** [comment]
- intro: "DaoCloud是业界领先的企业级容器云平台和解决方案提供商，致力于以Docker为代表的容器技术，为企业打造面向下一代互联网应用的交付和运维平台，帮助客户实现云端持续创新。DaoCloud采用混合云模式，以云端SaaS化容器管理平台，对接各类主机资源，构建跨云跨网的容器主机资源池，提供全流程标准化的应用持续集成、镜像构建、发布管理和容器运维服务。DaoCloud在开发运维联动、渐进式混合云构建、大规模高并发集群、微服务架构设计、分布式应用运维等场景拥有丰富经验和成功案例。DaoCloud总部位于中国上海，并在北京设有分支机构。"
- intro_en: "DaoCloud is a leading provider of enterprise cloud container platforms and solutions, focus on Docker and other container technologies to build the next generation internet applications. DaoCloud use hybrid cloud model, cloud-based container management SaaS platform, docking host all kinds of resources to build cross-cloud across the web container host resource pools. DaoCloud have a lot of success cases in the development of operation and maintenance, incremental build hybrid clouds, large-scale high concurrency clusters, micro-services architecture design, operation and maintenance of distributed applications. DaoCloud offices located in both Shanghai and Beijing."

大妈，不好意思，实在编不下去了，上面都是我乱写的。

**Comment by ZoomQuiet** [comment]
喂!
公司标准 自述哪,
难道没有一个统一稿件的?!

2015-09-03 17:51 GMT+08:00 haosdent notifications@github.com:

> - intro:
>   "DaoCloud是业界领先的企业级容器云平台和解决方案提供商，致力于以Docker为代表的容器技术，为企业打造面向下一代互联网应用的交付和运维平台，帮助客户实现云端持续创新。DaoCloud采用混合云模式，以云端SaaS化容器管理平台，对接各类主机资源，构建跨云跨网的容器主机资源池，提供全流程标准化的应用持续集成、镜像构建、发布管理和容器运维服务。DaoCloud在开发运维联动、渐进式混合云构建、大规模高并发集群、微服务架构设计、分布式应用运维等场景拥有丰富经验和成功案例。DaoCloud总部位于中国上海，并在北京设有分支机构。"
> - intro_en: "DaoCloud is a leading provider of enterprise cloud
>   container platforms and solutions, focus on Docker and other container
>   technologies to build the next generation internet applications. DaoCloud
>   use hybrid cloud model, cloud-based container management SaaS platform,
>   docking host all kinds of resources to build cross-cloud across the web
>   container host resource pools. DaoCloud have a lot of success cases in the
>   development of operation and maintenance, incremental build hybrid clouds,
>   large-scale high concurrency clusters, micro-services architecture design,
>   operation and maintenance of distributed applications. DaoCloud offices
>   located in both Shanghai and Beijing."
> 
> 大妈，不好意思，实在编不下去了，上面都是我乱写的。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/79#issuecomment-137394966.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by haosdent** [comment]
DaoCloud的童鞋可能有，我不是DaoCloud的。哈哈

**Comment by ZoomQuiet** [comment]
有 PR [Finished Engish translation by beyondliu · Pull Request #2 · PyConChina/staticpycon ](https://github.com/PyConChina/staticpycon/pull/2)

但是无法合并哪,,,
