### ISSUE TITLE
[speech]Sh: 戒空

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#80]
# 姜继忠，花名戒空

~ 09年加入阿里，并一直担任ACE的技术专家角色，负责了ACE底层的架构与开发工作，也是Python的忠实用户。
## 介绍阿里云ACE的Python环境的使用和架构设计实践。

![ali_jirkong](https://cloud.githubusercontent.com/assets/22494/9404917/ef170310-4825-11e5-8237-caeb165a373c.png)

**Comment by newmike** [comment]
阿里巴巴 ACE技术专家？
