### ISSUE TITLE
[提案]PyConChina推广文案大纲

### ISSUE THREAD

**Issue by newmike** [PyConChina/PyConCN#85]
以下是今年大会预发文案的大纲，有其它提议，请补充！

大纲
1. Python特色简介（吊起好奇心与同理心）
2. PyCon简介（讲历史，往年举办情况，发媒体报道链接）
3. 今年PyCon大会特色（三城联办，还有苏州杭州加进来，就不说了？），讲师简介及背景，门票包含餐饮及T恤
4. 技术参会者（Python爱好者）能收获什么，比如得到技术大牛的现场指导，比如和同样使用Python的基友现场交流！
5. 如果参会者是创业者，也可以来现场寻找技术合作伙伴~

**Comment by newmike** [comment]
PyCon大会就是现在相当火的开源编程语言Python的全球性的盛会，PyConChina 是由 CPyUG(华蠎用户组)获得授权举办的中国PyCon年会. 迄今已是第五届, 由PyChina.org发起,CPyUG/TopGeek 等社区协同,在2015年 9月12日（上海），9月13日（广州），9月19日（北京）分别举办! 无论您偏好哪种编程语言, 都欢迎来参加这场完全由Python中国社区组织的欢乐集会！
每年的PyConChina都有很多技术大牛出没! 今年也不例外！说到这里，今年大会都有哪些看点呢？
电商领域 会有来自国内阿里、1号店这些电商行业的领军企业的技术专家做技术分享！
大数据领域 有来自美国纳斯达克第一家纯大数据的上市公司Splunk的Tech Lead做技术分享！
云存储领域 有来自国内的几家知名的云存储公司：云智慧、七牛、DaoCloud的技术牛人、高级架构师甚或创始人来做关于Python与云存储的分享！
游戏领域 有来自Demonware（动视暴雪）的 自动化专家来做Python数据自动化管理分享！
机器人领域 有来自仪酷智能的机器人专家为大家分享如何用Python快速构建机器人系统!
职业规划领域 有来自猎聘网的高管来分享基于猎聘大数据的Python工程师职业发展研究，帮你理清未来职业规划！
社交通讯领域 -来自国内社交软件之王 - 腾讯微信的运营开发工程师为大家揭秘微信开发运维的技术内幕！
信息安全领域 有来自多家信息安全领域的大牛分享如何用Python做安全编码
编程教育领域 有多年经验的技术专家来分享怎么让小朋友通过Python爱上编程！
前网易技术大拿， <编写高质量代码：改善Python程序的91个建议>作者，现在自主创业的大牛来分享什么是Cython，用Cython封装C++代码为Python模块的一点经验等等！
前新浪及Zynga的技术大拿 <QPthon>作者来为大家分享怎么用 QPython 极速开发安卓App ！
资深 python 开发者，<高效能服务器 eurasia> 的作者来给大伙再说点儿有趣儿的事儿！
国际友人在线分享 来自台大的朋友来分享如何用 jieba来做搜索，以及台湾Python社团的现状，带大家开阔下视野！

以上仅仅列出了今年PyConChina大会的一部分内容，更多详细内容请关注大会官网！
 http://cn.pycon.org/

除了以上各位大拿的精彩分享外，今年大会参会者的其它福利：
所有参会者均会获赠价值99元的大会纪念苦短衫一件！
所有参会者均有免费午餐及茶歇！在此环节，各位可以与远道而来的嘉宾有机会进行面对面沟通交流。

今天(8/31)是PyCon大会特价99元早鸟票的最后一天，有兴趣参会的朋友，赶紧抓住机会啊~

上海场报名

广州场报名

北京场报名

PS: 如果想知道前几届活动的详细信息，可以登录大会官网http://cn.pycon.org/ 查看往届情况。

**Comment by ZoomQuiet** [comment]
太复杂了,
应该 140字/500字两种,可以在不同渠道高速传播的,,,

今天是 earlybird 最后一天,这就应该是今天最大的热点消息哪,,,,

**Comment by newmike** [comment]
精简版：
PyConChina2015-Pythoner的盛会！即将在2015年 9月12日（上海），9月13日（广州），9月19日（北京）分别举办! 无论您偏好哪种编程语言, 都欢迎来参加这场完全由Python中国社区组织的欢乐集会！ 今天(8/31)是PyCon大会特价99元早鸟票的最后一天，速度来抢票了！ 售票地址：http://event.31huiyi.com/118022165
