### ISSUE TITLE
页面静态化的实现

### ISSUE THREAD

**Issue by limodou** [PyConChina/PyConCN#9]
### 需求分析
- 因为更新频率不高，所以考虑页面静态化
### 设计
- 是否可以考虑使用nginx的X-SendFile机制，这样view仍继续处理，如果内容没有变化，则输出x-sendfile的头，转向静态化页面。这样可能容易实现。
- 如果内容有变化，则删除对应的静态文件，因此要考虑如何查找静态文件？因为一个内容的变化，可能影响多个页面。
- 内容生成考虑使用类似缓存的机制，不需要预先生成，而是随着访问来生成，这样第一次可能会慢，以后就直接使用静态化的内容了。
- 如何识别内容变化。
  - 首先定义静态文件名规则，根据url来转义，将所有`'/'`转为`'_'`，然后再添加 `_token` ，其中token是根据当前页面所对应的元素token合并而成。（通过MD5算法）
  - 其次，定义页面相关元素集成。每个可编辑项，如：赞助商，活动等都对应一个唯一的key，开始可以没有。如果发生变化，则利用UUID生成一个token，写入缓存。这样每个key都有一个token。如果发生变化，token值将改变。一个页面将对应一个或多个key。可以考虑把对应关系存入settings.ini中。
- 如何比较？因为静态文件名中将带有合成后的md5值，所以每次请求过来，将根据关联key来动态生成合成token，然后与文件名中的token比较，如果一致，说明没有变化，则直接返回。如果不同，则说明有变化，重新生成静态文件，然后返回。

**Comment by gfreezy** [comment]
页面静态化是为了提高性能？  但是这里的性能应该是没有什么问题，为了多余的一点点性能而做优化是不是没那么必要？

**Comment by limodou** [comment]
2012/8/25 Alex.F notifications@github.com

> 页面静态化是为了提高性能？ 但是这里的性能应该是没有什么问题，为了多余的一点点性能而做优化是不是没那么必要？
> 
> 未来的首页将有一些是动态的内容，比如赞助商，演讲主题等。可能是性能没有什么问题，但是到底怎么样不太清楚。而且这种是通用的机制，如果做出来，可以为其它的应用所复用。

## 

I like python!
UliPad <<The Python Editor>>: http://code.google.com/p/ulipad/
UliWeb <<simple web framework>>: https://github.com/limodou/uliweb
My Blog: http://my.oschina.net/limodou

**Comment by ZoomQuiet** [comment]
其实,主要是考虑到备份/部署/迁移的方便,
- 其实: "首页将有一些是动态的内容，比如赞助商，演讲主题等" 这些也是静态的,一但确认基本再也不会修订
- 静态化的最大好处是可以随时部署到 github/gitcafe/赞助主机 等等上,并配置好负载均衡
- 只要有一台主机,甚至于,任何一个维护人员的本地主机就可以完成内容的同步,渲染,发布...

**Comment by ZoomQuiet** [comment]
先用 MkDocs 完成重构
[PyConChina/MkDoc4PyCon - GitCafe](https://gitcafe.com/PyConChina/MkDoc4PyCon/blob/master/README.md)

UliWeb 持续学习,用作真实的后台吧...
