### ISSUE TITLE
[31huiyi] 纪念TEE 单独创建入口

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#95]
## 背景
- 往年苦短衫都是只有门票附加
- 但是,大会后总是有人垂涎想再买
- 所以,今年特别多制备了些,附加在门票页面可以单独购买:
  - [PyConChina 2015 中国大会 广州场_议程_报名_门票 - 31会议](http://event.31huiyi.com/118545334)
## 现象
- 但是,大多数人无法理解这是可以单独购买的 TEE
- 因为,从官网没有单独的入口,只想买 TEE 不想参会的就没有理由进入门票页面!
## 方案
- 在 31会议上 创建单独的入口
  - 只有 纪念 TEE 的特种票种
  - 要求详细的快递信息
  - 尺寸,以及意外处置
  - 生产等待情况

**Comment by newmike** [comment]
我可不可以淘宝开店来卖？ 这样好点

**Comment by ZoomQuiet** [comment]
最好统一在好传播的,
taobao 名声...
另外,那个微店的合作呢?

On Wed, Sep 2, 2015 at 11:07 AM, Mike Zhang notifications@github.com
wrote:

> 我可不可以淘宝开店来卖？ 这样好点
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/95#issuecomment-136920835.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by newmike** [comment]
https://item.taobao.com/item.htm?id=521694071295
这是淘宝的购买链接，你可以放到官网~ 简单做的，回头有时间再调下。
