### ISSUE TITLE
官网会场地图链接增补

### ISSUE THREAD

**Issue by ZoomQuiet** [PyConChina/PyConCN#96]
北京/上海 的地址信息,交通,以及地图链接请回复提交在此,
以便增补官网
- 地图使用高德的 ;-)

**Comment by newmike** [comment]
上海场地址： 上海市浦东新区博云路2号浦软大厦

http://f.amap.com/0FFE0i

**Comment by newmike** [comment]
北京场地址： 北京市东城区美术馆后街77号(近亮果厂胡同)
http://f.amap.com/0B9E8O

**Comment by ZoomQuiet** [comment]
广州的是:

UC优视广州公司
电话 : 020-66824888 邮编 : 510627
地址 : 广州市天河区黄埔大道西平云路163号广电平云广场B塔

http://f.amap.com/042E3U
