### ISSUE TITLE
用 QPython 极速开发 安卓 App  River

### ISSUE THREAD

**Issue by newmike** [PyConChina/PyConCN#98]
广州和北京日程里的这个嘉宾名称不一致

用 QPython 极速开发 安卓 App 
River

用 QPython 极速开发 安卓 App 
曲池峰

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)
是两位创始人,分别进行演讲

On Wed, Sep 2, 2015 at 5:28 PM, Mike Zhang notifications@github.com wrote:

> 广州和北京日程里的这个作者名称不一致
> 
> 用 QPython 极速开发 安卓 App
> River
> 
> 用 QPython 极速开发 安卓 App
> 曲池峰
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/PyConCN/issues/98.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
